"""add_webhook_fields_to_organizations

Revision ID: 5b67e464f6cb
Revises: 79b9cbab51f2
Create Date: 2026-02-19 14:57:36.562636+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b67e464f6cb"
down_revision: str | None = "79b9cbab51f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("webhook_url", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("webhook_secret", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_column("webhook_secret")
        batch_op.drop_column("webhook_url")

    # ### end Alembic commands ###
