"""add model_builder_documents table

Revision ID: b3c8d1e2f4a5
Revises: a2e8a91a0405
Create Date: 2026-02-20 08:43:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c8d1e2f4a5'
down_revision: Union[str, None] = 'a2e8a91a0405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_builder_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canvas_json', sa.JSON(), nullable=False),
    sa.Column('model_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_builder_documents', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_model_builder_documents_organization_id'),
            ['organization_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_builder_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_builder_documents_organization_id'))

    op.drop_table('model_builder_documents')
    # ### end Alembic commands ###
