"""initial_schema

Revision ID: 79b9cbab51f2
Revises: 
Create Date: 2026-02-19 14:24:25.220363+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b9cbab51f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date', name='uq_currency_date')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_rate_date'), ['rate_date'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('credits_used_month', sa.Integer(), nullable=False),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('credits_earned', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('bank_iban', sa.String(), nullable=True),
    sa.Column('bank_swift', sa.String(), nullable=True),
    sa.Column('bank_holder_name', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_private_plugins', sa.Integer(), nullable=False),
    sa.Column('ai_builder_enabled', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_public_profile', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    op.create_table('credit_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('earned_balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('amount_eur', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('buyer_organization_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('model_catalog',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('generator_type', sa.String(length=64), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('input_fields', sa.JSON(), nullable=False),
    sa.Column('example_input', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('author_organization_id', sa.String(length=64), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('credits_per_execution', sa.Integer(), nullable=False),
    sa.Column('total_activations', sa.Integer(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('avg_execution_time_ms', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_catalog_author_organization_id'), ['author_organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_catalog_category'), ['category'], unique=False)
        batch_op.create_index('ix_model_catalog_category_status', ['category', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_catalog_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_catalog_is_official'), ['is_official'], unique=False)
        batch_op.create_index('ix_model_catalog_official_featured', ['is_official', 'is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_catalog_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_build_plugins', sa.Boolean(), nullable=False),
    sa.Column('builder_tier', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('is_public_profile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_slug'), ['slug'], unique=True)

    op.create_table('withdrawal_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('amount_type', sa.String(), nullable=False),
    sa.Column('amount_value', sa.Float(), nullable=True),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.Column('next_execution', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_schedules_organization_id'), ['organization_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('model_reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('catalog_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('report_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['model_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_model_review_catalog_rating', ['catalog_id', 'rating'], unique=False)
        batch_op.create_index('ix_model_review_user_catalog', ['user_id', 'catalog_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_model_reviews_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_reviews_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notification_user_unread', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organization_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('catalog_id', sa.String(length=64), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('private_definition', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('total_credits_used', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_price_eur', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['model_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_models', schema=None) as batch_op:
        batch_op.create_index('ix_org_model_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('ix_org_model_org_catalog', ['organization_id', 'catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_models_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('recent_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_id', name='uq_user_model_recent')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('problem_type', sa.String(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_problem_type'), ['problem_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_favorites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_id', name='uq_user_model_favorite')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('withdrawal_type', sa.String(), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('credits_per_eur', sa.Integer(), nullable=False),
    sa.Column('eur_amount', sa.Float(), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('local_amount', sa.Float(), nullable=False),
    sa.Column('bank_iban', sa.String(), nullable=True),
    sa.Column('bank_swift', sa.String(), nullable=True),
    sa.Column('bank_holder_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['withdrawal_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawals_organization_id'), ['organization_id'], unique=False)

    op.create_table('model_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_model_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('executed_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('solver_status', sa.String(length=32), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('credits_base', sa.Integer(), nullable=False),
    sa.Column('credits_compute', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('is_async', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_model_id'], ['organization_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_executions', schema=None) as batch_op:
        batch_op.create_index('ix_model_exec_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index('ix_model_exec_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_executions_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_executions_organization_model_id'), ['organization_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_executions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_executions_status'))
        batch_op.drop_index(batch_op.f('ix_model_executions_organization_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_model_executions_created_at'))
        batch_op.drop_index(batch_op.f('ix_model_executions_celery_task_id'))
        batch_op.drop_index('ix_model_exec_status_created')
        batch_op.drop_index('ix_model_exec_org_created')

    op.drop_table('model_executions')
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_organization_id'))

    op.drop_table('withdrawals')
    op.drop_table('user_favorites')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_usage_records_problem_type'))
        batch_op.drop_index(batch_op.f('ix_usage_records_organization_id'))

    op.drop_table('usage_records')
    op.drop_table('recent_models')
    with op.batch_alter_table('organization_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_models_created_at'))
        batch_op.drop_index(batch_op.f('ix_organization_models_catalog_id'))
        batch_op.drop_index('ix_org_model_org_catalog')
        batch_op.drop_index('ix_org_model_org_active')

    op.drop_table('organization_models')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('ix_notification_user_unread')
        batch_op.drop_index('ix_notification_user_created')

    op.drop_table('notifications')
    with op.batch_alter_table('model_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_reviews_organization_id'))
        batch_op.drop_index(batch_op.f('ix_model_reviews_created_at'))
        batch_op.drop_index(batch_op.f('ix_model_reviews_catalog_id'))
        batch_op.drop_index('ix_model_review_user_catalog')
        batch_op.drop_index('ix_model_review_catalog_rating')

    op.drop_table('model_reviews')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('withdrawal_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_schedules_organization_id'))

    op.drop_table('withdrawal_schedules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_slug'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('model_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_catalog_status'))
        batch_op.drop_index('ix_model_catalog_official_featured')
        batch_op.drop_index(batch_op.f('ix_model_catalog_is_official'))
        batch_op.drop_index(batch_op.f('ix_model_catalog_created_at'))
        batch_op.drop_index('ix_model_catalog_category_status')
        batch_op.drop_index(batch_op.f('ix_model_catalog_category'))
        batch_op.drop_index(batch_op.f('ix_model_catalog_author_organization_id'))

    op.drop_table('model_catalog')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_created_at'))

    op.drop_table('credit_transactions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_exchange_rates_currency'))

    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
