"""P1.5 F2 — marketplace-fusion schema: the listing facet + additive forward FKs.

Additive-only, no behavior change (the fusion cutover is F4, behind
``MARKETPLACE_FUSION_ENABLED``):

- ``model_project_listings`` — the 1:1 marketplace FACET of a ModelProject
  (PK == FK → model_projects, ON DELETE CASCADE). Mirrors the surviving
  ``model_catalog`` listing columns so the F3 backfill is a near-direct copy.
- nullable ``model_project_id`` forward-link columns (FK → model_projects,
  ON DELETE CASCADE) on model_reviews / model_view_events / user_favorites /
  recent_models, so reviews/favorites/recents/impressions can point at the
  unified Model once F4 dual-writes them (legacy rows keep only their catalog id).

Hand-written (NOT autogenerated) so it carries ONLY these additions — the repo
has pre-existing ORM↔DB drift (ADR-008 money columns still in the DB, some index
renames) that a full autogenerate would sweep in.

Revision ID: 20260712_p15_listings
Revises: 20260712_llmconv_ondelete
Create Date: 2026-07-12
"""

import sqlalchemy as sa
from alembic import op

revision = "20260712_p15_listings"
down_revision = "20260712_llmconv_ondelete"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "model_project_listings",
        sa.Column("model_project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("scenario_description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("generator_type", sa.String(length=64), nullable=True),
        sa.Column("input_schema", sa.JSON(), nullable=True),
        sa.Column("input_fields", sa.JSON(), nullable=True),
        sa.Column("example_input", sa.JSON(), nullable=True),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pinned_version_id", sa.String(length=64), nullable=True),
        sa.Column("author_organization_id", sa.String(length=64), nullable=True),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("total_activations", sa.Integer(), nullable=False),
        sa.Column("total_executions", sa.Integer(), nullable=False),
        sa.Column("avg_execution_time_ms", sa.Float(), nullable=True),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("avg_rating", sa.Float(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("screenshot_urls", sa.JSON(), nullable=True),
        sa.Column("section_overview", sa.Text(), nullable=True),
        sa.Column("section_features", sa.Text(), nullable=True),
        sa.Column("section_how_it_works", sa.Text(), nullable=True),
        sa.Column("section_example_io", sa.Text(), nullable=True),
        sa.Column("section_changelog", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["model_project_id"], ["model_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pinned_version_id"], ["model_project_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("model_project_id"),
    )
    op.create_index(
        op.f("ix_model_project_listings_author_organization_id"),
        "model_project_listings",
        ["author_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_project_listings_category"),
        "model_project_listings",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_project_listings_created_at"),
        "model_project_listings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_project_listings_is_official"),
        "model_project_listings",
        ["is_official"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_project_listings_status"),
        "model_project_listings",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_mpl_category_status", "model_project_listings", ["category", "status"], unique=False
    )
    op.create_index(
        "ix_mpl_official_featured",
        "model_project_listings",
        ["is_official", "is_featured"],
        unique=False,
    )

    # Additive forward-link columns (FK → model_projects, nullable; the FK is created
    # inline with the column so a downgrade drops it together with the column).
    for table in ("model_reviews", "model_view_events", "user_favorites", "recent_models"):
        op.add_column(
            table,
            sa.Column(
                "model_project_id",
                sa.String(length=64),
                sa.ForeignKey("model_projects.id", ondelete="CASCADE"),
                nullable=True,
            ),
        )
        op.create_index(
            op.f(f"ix_{table}_model_project_id"), table, ["model_project_id"], unique=False
        )


def downgrade() -> None:
    for table in ("recent_models", "user_favorites", "model_view_events", "model_reviews"):
        op.drop_index(op.f(f"ix_{table}_model_project_id"), table_name=table)
        op.drop_column(table, "model_project_id")

    op.drop_index("ix_mpl_official_featured", table_name="model_project_listings")
    op.drop_index("ix_mpl_category_status", table_name="model_project_listings")
    op.drop_index(op.f("ix_model_project_listings_status"), table_name="model_project_listings")
    op.drop_index(
        op.f("ix_model_project_listings_is_official"), table_name="model_project_listings"
    )
    op.drop_index(op.f("ix_model_project_listings_created_at"), table_name="model_project_listings")
    op.drop_index(op.f("ix_model_project_listings_category"), table_name="model_project_listings")
    op.drop_index(
        op.f("ix_model_project_listings_author_organization_id"),
        table_name="model_project_listings",
    )
    op.drop_table("model_project_listings")
