"""add_invoices_table

Revision ID: a2e8a91a0405
Revises: 5b67e464f6cb
Create Date: 2026-02-19 15:10:30.765812+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e8a91a0405'
down_revision: Union[str, None] = '5b67e464f6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('invoice_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('org_email', sa.String(length=200), nullable=True),
    sa.Column('org_plan', sa.String(length=30), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('subtotal_eur', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount_eur', sa.Float(), nullable=False),
    sa.Column('total_eur', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('total_local', sa.Float(), nullable=False),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))

    op.drop_table('invoices')
    # ### end Alembic commands ###
