// AUTO-GENERATED by scripts/gen_landing_analysis.py — do not edit by hand.
//
// A real solve of a quarterly production plan for a power-electronics plant,
// with the exact analysis JAOT computes afterwards: binding constraints, slack,
// and objective contributions derived from x* and the problem data — not shadow
// prices.
//
// Regenerate with: python scripts/gen_landing_analysis.py

export interface AnalysisConstraint {
  /** Translation key for the constraint's display name. */
  readonly key: string;
  readonly activity: number;
  readonly capacity: number;
  readonly slack: number;
  /** Percent of capacity consumed. */
  readonly utilization: number;
  readonly binding: boolean;
  readonly operator: string;
}

export interface AnalysisContribution {
  readonly key: string;
  readonly units: number;
  readonly margin: number;
  readonly contribution: number;
  /** Percent of the objective this term accounts for. */
  readonly share: number;
  /** Per-unit draw on each binding resource, keyed by constraint key. */
  readonly usage: Readonly<Record<string, number>>;
}

export interface AnalysisShowcase {
  readonly objective: number;
  readonly status: string;
  readonly constraints: readonly AnalysisConstraint[];
  readonly contributions: readonly AnalysisContribution[];
  /** The capacity limit furthest from running out, and by how much. */
  readonly loosest: {
    readonly key: string;
    readonly slack: number;
  };
  readonly meta: {
    readonly products: number;
    readonly unitsBuilt: number;
    readonly bindingCount: number;
    readonly totalConstraints: number;
    readonly nodes: number;
    readonly solver: string;
  };
}

export const ANALYSIS_SHOWCASE: AnalysisShowcase = {
  "objective": 15366800.0,
  "status": "optimal",
  "constraints": [
    {
      "key": "smtHours",
      "activity": 58570,
      "capacity": 58570,
      "slack": 0,
      "utilization": 100.0,
      "binding": true,
      "operator": "<="
    },
    {
      "key": "burnInHours",
      "activity": 43620,
      "capacity": 43620,
      "slack": 0,
      "utilization": 100.0,
      "binding": true,
      "operator": "<="
    },
    {
      "key": "mcuChips",
      "activity": 147010,
      "capacity": 259580,
      "slack": 112570,
      "utilization": 56.6,
      "binding": false,
      "operator": "<="
    },
    {
      "key": "sicModules",
      "activity": 86040,
      "capacity": 86040,
      "slack": 0,
      "utilization": 100.0,
      "binding": true,
      "operator": "<="
    },
    {
      "key": "testHours",
      "activity": 36160,
      "capacity": 44090,
      "slack": 7930,
      "utilization": 82.0,
      "binding": false,
      "operator": "<="
    },
    {
      "key": "coatingHours",
      "activity": 29870,
      "capacity": 33160,
      "slack": 3290,
      "utilization": 90.1,
      "binding": false,
      "operator": "<="
    },
    {
      "key": "telemetryContract",
      "activity": 8660,
      "capacity": 3500,
      "slack": 5160,
      "utilization": 40.4,
      "binding": false,
      "operator": ">="
    }
  ],
  "contributions": [
    {
      "key": "tractionInverter",
      "units": 0,
      "margin": 2450,
      "contribution": 0,
      "share": 0.0,
      "usage": {
        "smtHours": 5,
        "burnInHours": 10,
        "sicModules": 24
      }
    },
    {
      "key": "batteryMonitor",
      "units": 0,
      "margin": 1780,
      "contribution": 0,
      "share": 0.0,
      "usage": {
        "smtHours": 4,
        "burnInHours": 8,
        "sicModules": 15
      }
    },
    {
      "key": "chargeModule",
      "units": 0,
      "margin": 1320,
      "contribution": 0,
      "share": 0.0,
      "usage": {
        "smtHours": 4,
        "burnInHours": 5,
        "sicModules": 11
      }
    },
    {
      "key": "gridInverter",
      "units": 7460,
      "margin": 960,
      "contribution": 7161600,
      "share": 46.6,
      "usage": {
        "smtHours": 3,
        "burnInHours": 3,
        "sicModules": 7
      }
    },
    {
      "key": "motorDrive",
      "units": 6290,
      "margin": 740,
      "contribution": 4654600,
      "share": 30.3,
      "usage": {
        "smtHours": 3,
        "burnInHours": 2,
        "sicModules": 4
      }
    },
    {
      "key": "telemetryUnit",
      "units": 8660,
      "margin": 410,
      "contribution": 3550600,
      "share": 23.1,
      "usage": {
        "smtHours": 2,
        "burnInHours": 1,
        "sicModules": 1
      }
    },
    {
      "key": "sensorHub",
      "units": 0,
      "margin": 260,
      "contribution": 0,
      "share": 0.0,
      "usage": {
        "smtHours": 2,
        "burnInHours": 1,
        "sicModules": 0
      }
    }
  ],
  "loosest": {
    "key": "mcuChips",
    "slack": 112570
  },
  "meta": {
    "products": 7,
    "unitsBuilt": 22410,
    "bindingCount": 3,
    "totalConstraints": 7,
    "nodes": 1,
    "solver": "SCIP"
  }
} as const;
