// AUTO-GENERATED by scripts/gen_landing_analysis.py — do not edit by hand.
//
// A real solve of a small production-planning instance, with the exact analysis
// JAOT computes afterwards: binding constraints, slack, and objective
// contributions derived from x* and the problem data — not shadow prices.
//
// Regenerate with: python scripts/gen_landing_analysis.py

export interface AnalysisConstraint {
  /** Translation key for the constraint's display name. */
  readonly key: string;
  readonly activity: number;
  readonly capacity: number;
  readonly slack: number;
  /** Percent of capacity consumed. */
  readonly utilization: number;
  readonly binding: boolean;
  readonly operator: string;
}

export interface AnalysisContribution {
  readonly key: string;
  readonly units: number;
  readonly margin: number;
  readonly contribution: number;
  /** Percent of the objective this term accounts for. */
  readonly share: number;
  /** Per-unit draw on each binding resource, keyed by constraint key. */
  readonly usage: Readonly<Record<string, number>>;
}

export interface AnalysisShowcase {
  readonly objective: number;
  readonly status: string;
  readonly constraints: readonly AnalysisConstraint[];
  readonly contributions: readonly AnalysisContribution[];
  readonly meta: {
    readonly products: number;
    readonly bindingCount: number;
    readonly totalConstraints: number;
    readonly solver: string;
  };
}

export const ANALYSIS_SHOWCASE: AnalysisShowcase = {
  "objective": 5580.0,
  "status": "optimal",
  "constraints": [
    {
      "key": "machineHours",
      "activity": 260,
      "capacity": 400,
      "slack": 140,
      "utilization": 65.0,
      "binding": false,
      "operator": "<="
    },
    {
      "key": "craftHours",
      "activity": 300,
      "capacity": 300,
      "slack": 0,
      "utilization": 100.0,
      "binding": true,
      "operator": "<="
    },
    {
      "key": "oakPlanks",
      "activity": 520,
      "capacity": 520,
      "slack": 0,
      "utilization": 100.0,
      "binding": true,
      "operator": "<="
    },
    {
      "key": "chairContract",
      "activity": 76,
      "capacity": 12,
      "slack": 64,
      "utilization": 15.8,
      "binding": false,
      "operator": ">="
    }
  ],
  "contributions": [
    {
      "key": "desks",
      "units": 0,
      "margin": 120,
      "contribution": 0,
      "share": 0.0,
      "usage": {
        "craftHours": 7,
        "oakPlanks": 12
      }
    },
    {
      "key": "tables",
      "units": 0,
      "margin": 80,
      "contribution": 0,
      "share": 0.0,
      "usage": {
        "craftHours": 5,
        "oakPlanks": 9
      }
    },
    {
      "key": "shelves",
      "units": 36,
      "margin": 60,
      "contribution": 2160,
      "share": 38.7,
      "usage": {
        "craftHours": 2,
        "oakPlanks": 6
      }
    },
    {
      "key": "chairs",
      "units": 76,
      "margin": 45,
      "contribution": 3420,
      "share": 61.3,
      "usage": {
        "craftHours": 3,
        "oakPlanks": 4
      }
    }
  ],
  "meta": {
    "products": 4,
    "bindingCount": 2,
    "totalConstraints": 4,
    "solver": "SCIP"
  }
} as const;
