// AUTO-GENERATED by scripts/gen_landing_catalog.py — do not edit by hand.
//
// Counted from app/data/templates/*.yaml, so the figures on the home page are
// the catalogue itself rather than a claim about it.
//
// Regenerate with: python scripts/gen_landing_catalog.py

export interface CatalogSector {
  readonly name: string;
  readonly count: number;
}

export interface CatalogFeatured {
  readonly name: string;
  readonly sector: string;
  readonly variables: number | null;
}

export interface CatalogSummary {
  readonly total: number;
  readonly sectors: readonly CatalogSector[];
  readonly featured: readonly CatalogFeatured[];
  readonly meta: {
    readonly sectorCount: number;
    readonly files: number;
  };
}

export const CATALOG_SUMMARY: CatalogSummary = {
  "total": 102,
  "sectors": [
    {
      "name": "Finance & Investment",
      "count": 5
    },
    {
      "name": "Logistics & Distribution",
      "count": 5
    },
    {
      "name": "Human Resources & Workforce",
      "count": 4
    },
    {
      "name": "Manufacturing & Production",
      "count": 4
    },
    {
      "name": "Aerospace",
      "count": 3
    },
    {
      "name": "Agriculture & Farming",
      "count": 3
    },
    {
      "name": "Chemical Engineering",
      "count": 3
    },
    {
      "name": "Construction",
      "count": 3
    },
    {
      "name": "Cutting & Packing",
      "count": 3
    },
    {
      "name": "Energy & Utilities",
      "count": 3
    },
    {
      "name": "Facility Location",
      "count": 3
    },
    {
      "name": "Food & Beverage",
      "count": 3
    },
    {
      "name": "Forestry",
      "count": 3
    },
    {
      "name": "General Purpose",
      "count": 3
    },
    {
      "name": "Government",
      "count": 3
    },
    {
      "name": "Healthcare & Nutrition",
      "count": 3
    },
    {
      "name": "Maritime",
      "count": 3
    },
    {
      "name": "Mining",
      "count": 3
    },
    {
      "name": "Network & Graph Optimization",
      "count": 3
    },
    {
      "name": "Pharmaceutical",
      "count": 3
    },
    {
      "name": "Railway",
      "count": 3
    },
    {
      "name": "Real Estate",
      "count": 3
    },
    {
      "name": "Retail & Commerce",
      "count": 3
    },
    {
      "name": "Supply Chain Management",
      "count": 3
    },
    {
      "name": "Telecommunications",
      "count": 3
    },
    {
      "name": "Transportation & Logistics",
      "count": 3
    },
    {
      "name": "Warehouse",
      "count": 3
    },
    {
      "name": "Water Management",
      "count": 3
    },
    {
      "name": "Advertising & Media",
      "count": 2
    },
    {
      "name": "Education & Academic",
      "count": 2
    },
    {
      "name": "Environmental & Sustainability",
      "count": 2
    },
    {
      "name": "Insurance",
      "count": 2
    },
    {
      "name": "Sports & Recreation",
      "count": 2
    },
    {
      "name": "Textile",
      "count": 2
    }
  ],
  "featured": [
    {
      "name": "Waste Collection Routing",
      "sector": "Environmental & Sustainability",
      "variables": 112
    },
    {
      "name": "Nurse Scheduling",
      "sector": "Healthcare & Nutrition",
      "variables": 112
    },
    {
      "name": "Project Scheduling",
      "sector": "Construction",
      "variables": 90
    },
    {
      "name": "Vehicle Routing (VRP)",
      "sector": "Logistics & Distribution",
      "variables": 84
    },
    {
      "name": "Fabric Cutting",
      "sector": "Textile",
      "variables": 50
    },
    {
      "name": "Warehouse Slotting",
      "sector": "Warehouse",
      "variables": 49
    }
  ],
  "meta": {
    "sectorCount": 34,
    "files": 34
  }
} as const;
