// AUTO-GENERATED by scripts/gen_landing_comparison.py — do not edit by hand.
//
// One real problem run by all five solvers under the terms the comparer
// imposes: same time limit, same gap tolerance, same thread count, one after
// another on one machine. The numbers are what JAOT's own adapters returned.
//
// The instance is a burn-in chamber loading plan for the same power-electronics
// plant the rest of this page solves. It is a bin-packing model on purpose: the
// assignment is symmetric, and how a solver handles that symmetry is what
// separates the five.
//
// Regenerate with: python scripts/gen_landing_comparison.py

export interface ComparisonRow {
  readonly solver: string;
  /** The solver's own verdict: optimal | feasible | time_limit | ... */
  readonly status: string;
  readonly objective: number | null;
  /** Best objective the solver proved could still exist. */
  readonly bound: number | null;
  readonly gap: number | null;
  /** Wall time around the whole call, building the solver's model included. */
  readonly wallMs: number;
  /** The adapter's own measure of the search alone. */
  readonly searchSeconds: number | null;
  readonly nodes: number | null;
  readonly iterations: number | null;
  /** How many times slower than the quickest solver that actually answered.
   *  Null for a run that came back without one: it was cut off, not slow. */
  readonly slowdown: number | null;
}

export interface ComparisonShowcaseMeta {
  readonly lots: number;
  readonly chambers: number;
  readonly chamberHours: number;
  /** Pairs of lots that share a fixture and so cannot share a chamber. */
  readonly fixturePairs: number;
  readonly variables: number;
  readonly constraints: number;
  readonly timeLimitSeconds: number;
  readonly gapTolerance: number;
  readonly threads: number;
  /** Cores on the machine that produced these seconds. */
  readonly cores: number;
}

export const COMPARISON_ROWS: readonly ComparisonRow[] = [
  {
    "solver": "scip",
    "status": "optimal",
    "objective": 17.0,
    "bound": 17.0,
    "gap": 0.0,
    "wallMs": 10857,
    "searchSeconds": 10.625850415031891,
    "nodes": 201,
    "iterations": 73617,
    "slowdown": 7.53
  },
  {
    "solver": "highs",
    "status": "optimal",
    "objective": 17.0,
    "bound": 17.0,
    "gap": 0.0,
    "wallMs": 1442,
    "searchSeconds": 1.4387575930450112,
    "nodes": 1,
    "iterations": 4214,
    "slowdown": 1.0
  },
  {
    "solver": "cbc",
    "status": "optimal",
    "objective": 17.0,
    "bound": 17.0,
    "gap": 0.0,
    "wallMs": 1704,
    "searchSeconds": 1.6971162229892798,
    "nodes": 776,
    "iterations": 16402,
    "slowdown": 1.18
  },
  {
    "solver": "glpk",
    "status": "time_limit",
    "objective": null,
    "bound": 17.0,
    "gap": null,
    "wallMs": 59916,
    "searchSeconds": 59.91472369298572,
    "nodes": 44838,
    "iterations": 313477,
    "slowdown": null
  },
  {
    "solver": "jaos",
    "status": "time_limit",
    "objective": null,
    "bound": 16.470238095238095,
    "gap": null,
    "wallMs": 60050,
    "searchSeconds": 60.050015664019156,
    "nodes": 1332,
    "iterations": 1057571,
    "slowdown": null
  }
] as const;

export const COMPARISON_META: ComparisonShowcaseMeta = {
  "lots": 60,
  "chambers": 22,
  "chamberHours": 168,
  "fixturePairs": 158,
  "variables": 1342,
  "constraints": 3558,
  "timeLimitSeconds": 60.0,
  "gapTolerance": 0.0001,
  "threads": 4,
  "cores": 12
} as const;

