// AUTO-GENERATED by scripts/gen_hero_trace.py — do not edit by hand.
//
// Every tour below is a solution SCIP actually found on a 24-stop routing
// instance (seed 7), and every bound is one it proved. The hero animates
// this trace, so the front page shows a real run rather than a mock-up.
//
// Regenerate with: python scripts/gen_hero_trace.py

export interface HeroTraceFrame {
  /** Stop indices in visiting order, closing back to the first. */
  readonly tour: readonly number[];
  /** Objective value of this incumbent (total route length). */
  readonly cost: number;
  /** Best proven lower bound when this incumbent was found. */
  readonly dual: number;
  /** Branch-and-bound nodes explored at that moment. */
  readonly nodes: number;
}

export interface HeroTraceCurvePoint {
  readonly nodes: number;
  readonly dual: number;
  readonly primal: number | null;
}

export interface HeroTrace {
  readonly points: readonly (readonly [number, number])[];
  readonly frames: readonly HeroTraceFrame[];
  readonly curve: readonly HeroTraceCurvePoint[];
  readonly meta: {
    readonly stops: number;
    readonly variables: number;
    readonly binaries: number;
    readonly optimum: number;
    readonly nodes: number;
    readonly status: string;
    readonly solver: string;
  };
}

export const HERO_TRACE: HeroTrace = {
  "points": [
    [
      34.5,
      19.27
    ],
    [
      63.28,
      12.37
    ],
    [
      53.16,
      38.18
    ],
    [
      11.1,
      50.65
    ],
    [
      9.3,
      44.16
    ],
    [
      12.15,
      13.98
    ],
    [
      43.36,
      78.76
    ],
    [
      16.89,
      25.65
    ],
    [
      61.21,
      89.4
    ],
    [
      56.79,
      40.91
    ],
    [
      91.91,
      10.1
    ],
    [
      81.55,
      31.49
    ],
    [
      18.69,
      16.37
    ],
    [
      33.15,
      77.82
    ],
    [
      21.9,
      57.18
    ],
    [
      62.22,
      38.77
    ],
    [
      54.2,
      11.53
    ],
    [
      11.24,
      24.12
    ],
    [
      65.88,
      43.63
    ],
    [
      33.64,
      57.53
    ],
    [
      45.88,
      32.38
    ],
    [
      75.91,
      67.51
    ],
    [
      27.48,
      56.55
    ],
    [
      52.22,
      83.01
    ]
  ],
  "frames": [
    {
      "tour": [
        0,
        2,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23
      ],
      "cost": 1072.22,
      "dual": 0.0,
      "nodes": 1
    },
    {
      "tour": [
        0,
        16,
        1,
        10,
        11,
        18,
        21,
        8,
        6,
        13,
        23,
        9,
        15,
        2,
        20,
        4,
        3,
        22,
        19,
        14,
        5,
        17,
        7,
        12
      ],
      "cost": 438.66,
      "dual": 332.32,
      "nodes": 1
    },
    {
      "tour": [
        0,
        12,
        5,
        17,
        7,
        4,
        3,
        14,
        22,
        19,
        13,
        6,
        23,
        8,
        21,
        18,
        15,
        11,
        10,
        1,
        16,
        2,
        9,
        20
      ],
      "cost": 344.71,
      "dual": 332.32,
      "nodes": 1
    },
    {
      "tour": [
        0,
        12,
        5,
        17,
        7,
        4,
        3,
        14,
        22,
        19,
        13,
        6,
        23,
        8,
        21,
        18,
        15,
        9,
        20,
        2,
        11,
        10,
        1,
        16
      ],
      "cost": 340.98,
      "dual": 332.55,
      "nodes": 23
    },
    {
      "tour": [
        0,
        12,
        5,
        17,
        7,
        4,
        3,
        14,
        22,
        19,
        13,
        6,
        23,
        8,
        21,
        18,
        15,
        9,
        2,
        20,
        11,
        10,
        1,
        16
      ],
      "cost": 338.19,
      "dual": 332.55,
      "nodes": 26
    }
  ],
  "curve": [
    {
      "nodes": 1,
      "dual": 0.0,
      "primal": null
    },
    {
      "nodes": 1,
      "dual": 332.32,
      "primal": 1072.22
    },
    {
      "nodes": 1,
      "dual": 332.32,
      "primal": 438.66
    },
    {
      "nodes": 1,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 2,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 3,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 4,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 5,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 6,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 7,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 8,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 9,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 10,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 11,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 12,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 13,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 14,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 15,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 16,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 17,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 18,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 19,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 20,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 21,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 22,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 23,
      "dual": 332.55,
      "primal": 344.71
    },
    {
      "nodes": 23,
      "dual": 332.55,
      "primal": 340.98
    },
    {
      "nodes": 24,
      "dual": 332.55,
      "primal": 340.98
    },
    {
      "nodes": 25,
      "dual": 332.55,
      "primal": 340.98
    },
    {
      "nodes": 26,
      "dual": 332.55,
      "primal": 340.98
    },
    {
      "nodes": 26,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 27,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 28,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 29,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 30,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 31,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 32,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 33,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 34,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 35,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 36,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 37,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 38,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 39,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 40,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 41,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 42,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 43,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 44,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 45,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 46,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 47,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 48,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 49,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 50,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 51,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 52,
      "dual": 332.55,
      "primal": 338.19
    },
    {
      "nodes": 53,
      "dual": 332.64,
      "primal": 338.19
    },
    {
      "nodes": 54,
      "dual": 332.64,
      "primal": 338.19
    },
    {
      "nodes": 55,
      "dual": 332.64,
      "primal": 338.19
    },
    {
      "nodes": 56,
      "dual": 332.64,
      "primal": 338.19
    },
    {
      "nodes": 57,
      "dual": 332.64,
      "primal": 338.19
    },
    {
      "nodes": 58,
      "dual": 333.81,
      "primal": 338.19
    },
    {
      "nodes": 59,
      "dual": 333.81,
      "primal": 338.19
    },
    {
      "nodes": 60,
      "dual": 333.81,
      "primal": 338.19
    },
    {
      "nodes": 61,
      "dual": 333.81,
      "primal": 338.19
    },
    {
      "nodes": 62,
      "dual": 333.84,
      "primal": 338.19
    },
    {
      "nodes": 63,
      "dual": 333.84,
      "primal": 338.19
    },
    {
      "nodes": 64,
      "dual": 333.84,
      "primal": 338.19
    },
    {
      "nodes": 65,
      "dual": 333.84,
      "primal": 338.19
    },
    {
      "nodes": 66,
      "dual": 333.84,
      "primal": 338.19
    },
    {
      "nodes": 67,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 68,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 69,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 70,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 71,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 72,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 73,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 74,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 75,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 76,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 77,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 78,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 79,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 80,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 81,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 82,
      "dual": 333.86,
      "primal": 338.19
    },
    {
      "nodes": 83,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 84,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 85,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 86,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 87,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 88,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 89,
      "dual": 334.3,
      "primal": 338.19
    },
    {
      "nodes": 90,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 91,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 92,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 93,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 94,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 95,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 96,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 97,
      "dual": 335.11,
      "primal": 338.19
    },
    {
      "nodes": 98,
      "dual": 335.63,
      "primal": 338.19
    },
    {
      "nodes": 99,
      "dual": 335.63,
      "primal": 338.19
    },
    {
      "nodes": 100,
      "dual": 335.63,
      "primal": 338.19
    },
    {
      "nodes": 101,
      "dual": 336.36,
      "primal": 338.19
    },
    {
      "nodes": 102,
      "dual": 338.19,
      "primal": 338.19
    }
  ],
  "meta": {
    "stops": 24,
    "variables": 576,
    "binaries": 552,
    "optimum": 338.19,
    "nodes": 102,
    "status": "optimal",
    "solver": "SCIP"
  }
} as const;
