// AUTO-GENERATED by scripts/gen_hero_trace.py — do not edit by hand.
//
// Every tour below is a solution SCIP actually found on a 48-stop routing
// instance (seed 7), and every bound is one it proved. The hero animates
// this trace, so the front page shows a real run rather than a mock-up.
//
// Regenerate with: python scripts/gen_hero_trace.py

export interface HeroTraceFrame {
  /** Stop indices in visiting order, closing back to the first. */
  readonly tour: readonly number[];
  /** Objective value of this incumbent (total route length). */
  readonly cost: number;
  /** Best proven lower bound when this incumbent was found. */
  readonly dual: number;
  /** Branch-and-bound nodes explored at that moment. */
  readonly nodes: number;
}

export interface HeroTraceCurvePoint {
  readonly nodes: number;
  readonly dual: number;
  readonly primal: number | null;
}

export interface HeroTrace {
  readonly points: readonly (readonly [number, number])[];
  readonly frames: readonly HeroTraceFrame[];
  readonly curve: readonly HeroTraceCurvePoint[];
  readonly meta: {
    readonly stops: number;
    readonly variables: number;
    readonly binaries: number;
    readonly optimum: number;
    readonly nodes: number;
    readonly status: string;
    readonly solver: string;
  };
}

export const HERO_TRACE: HeroTrace = {
  "points": [
    [
      34.5,
      19.27
    ],
    [
      63.28,
      12.37
    ],
    [
      53.16,
      38.18
    ],
    [
      11.1,
      50.65
    ],
    [
      9.3,
      44.16
    ],
    [
      12.15,
      13.98
    ],
    [
      43.36,
      78.76
    ],
    [
      16.89,
      25.65
    ],
    [
      61.21,
      89.4
    ],
    [
      56.79,
      40.91
    ],
    [
      91.91,
      10.1
    ],
    [
      81.55,
      31.49
    ],
    [
      18.69,
      16.37
    ],
    [
      33.15,
      77.82
    ],
    [
      21.9,
      57.18
    ],
    [
      62.22,
      38.77
    ],
    [
      54.2,
      11.53
    ],
    [
      11.24,
      24.12
    ],
    [
      65.88,
      43.63
    ],
    [
      33.64,
      57.53
    ],
    [
      45.88,
      32.38
    ],
    [
      75.91,
      67.51
    ],
    [
      27.48,
      56.55
    ],
    [
      52.22,
      83.01
    ],
    [
      70.19,
      31.34
    ],
    [
      92.26,
      16.39
    ],
    [
      42.79,
      72.63
    ],
    [
      19.37,
      49.03
    ],
    [
      9.45,
      64.8
    ],
    [
      73.28,
      56.43
    ],
    [
      83.04,
      33.61
    ],
    [
      67.19,
      58.3
    ],
    [
      57.03,
      46.15
    ],
    [
      79.92,
      89.13
    ],
    [
      47.72,
      64.45
    ],
    [
      11.34,
      67.73
    ],
    [
      62.95,
      93.39
    ],
    [
      78.33,
      31.04
    ],
    [
      39.95,
      64.84
    ],
    [
      7.99,
      46.63
    ],
    [
      20.79,
      16.3
    ],
    [
      11.19,
      73.6
    ],
    [
      17.38,
      27.79
    ],
    [
      40.4,
      82.69
    ],
    [
      13.09,
      45.53
    ],
    [
      54.35,
      83.74
    ],
    [
      78.1,
      82.03
    ],
    [
      30.5,
      42.55
    ]
  ],
  "frames": [
    {
      "tour": [
        0,
        2,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47
      ],
      "cost": 2092.55,
      "dual": 0.0,
      "nodes": 1
    },
    {
      "tour": [
        0,
        20,
        2,
        32,
        9,
        15,
        24,
        37,
        1,
        16,
        10,
        25,
        30,
        11,
        18,
        31,
        29,
        21,
        46,
        33,
        36,
        8,
        45,
        23,
        6,
        43,
        13,
        26,
        34,
        38,
        19,
        22,
        14,
        41,
        35,
        28,
        3,
        39,
        4,
        44,
        27,
        47,
        42,
        7,
        17,
        5,
        12,
        40
      ],
      "cost": 481.8,
      "dual": 444.94,
      "nodes": 40
    },
    {
      "tour": [
        0,
        16,
        1,
        10,
        25,
        30,
        11,
        37,
        24,
        15,
        2,
        20,
        9,
        32,
        18,
        31,
        29,
        21,
        46,
        33,
        36,
        8,
        45,
        23,
        6,
        43,
        13,
        26,
        34,
        38,
        19,
        22,
        14,
        41,
        35,
        28,
        3,
        39,
        4,
        44,
        27,
        47,
        42,
        7,
        17,
        5,
        12,
        40
      ],
      "cost": 453.46,
      "dual": 444.94,
      "nodes": 45
    },
    {
      "tour": [
        0,
        40,
        12,
        5,
        17,
        7,
        42,
        47,
        27,
        44,
        4,
        39,
        3,
        28,
        35,
        41,
        14,
        22,
        19,
        38,
        34,
        26,
        13,
        43,
        6,
        23,
        45,
        8,
        36,
        33,
        46,
        21,
        29,
        31,
        18,
        32,
        9,
        2,
        20,
        15,
        24,
        37,
        11,
        30,
        25,
        10,
        1,
        16
      ],
      "cost": 452.62,
      "dual": 445.13,
      "nodes": 332
    }
  ],
  "curve": [
    {
      "nodes": 1,
      "dual": 0.0,
      "primal": null
    },
    {
      "nodes": 1,
      "dual": 444.78,
      "primal": 2092.55
    },
    {
      "nodes": 1,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 2,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 3,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 4,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 5,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 6,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 7,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 8,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 9,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 10,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 11,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 12,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 13,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 14,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 15,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 16,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 17,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 18,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 19,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 20,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 21,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 22,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 23,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 24,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 25,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 26,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 27,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 28,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 29,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 30,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 31,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 32,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 33,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 34,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 35,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 36,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 37,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 38,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 39,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 40,
      "dual": 444.94,
      "primal": 2058.2
    },
    {
      "nodes": 40,
      "dual": 444.94,
      "primal": 481.8
    },
    {
      "nodes": 41,
      "dual": 444.94,
      "primal": 481.8
    },
    {
      "nodes": 42,
      "dual": 444.94,
      "primal": 481.8
    },
    {
      "nodes": 43,
      "dual": 444.94,
      "primal": 481.8
    },
    {
      "nodes": 44,
      "dual": 444.94,
      "primal": 481.8
    },
    {
      "nodes": 45,
      "dual": 444.94,
      "primal": 481.8
    },
    {
      "nodes": 45,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 46,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 47,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 48,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 49,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 50,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 51,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 52,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 53,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 54,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 55,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 56,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 57,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 58,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 59,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 60,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 61,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 62,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 63,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 64,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 65,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 66,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 67,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 68,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 69,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 70,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 71,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 72,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 73,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 74,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 75,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 76,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 77,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 78,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 79,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 80,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 81,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 82,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 83,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 84,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 85,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 86,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 87,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 88,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 89,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 90,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 91,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 92,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 93,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 94,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 95,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 96,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 97,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 98,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 99,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 100,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 101,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 102,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 103,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 104,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 105,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 106,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 107,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 108,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 109,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 110,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 111,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 112,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 113,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 114,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 115,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 116,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 117,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 118,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 119,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 120,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 121,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 122,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 123,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 124,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 125,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 126,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 127,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 128,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 129,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 130,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 131,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 132,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 133,
      "dual": 444.94,
      "primal": 453.46
    },
    {
      "nodes": 133,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 134,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 135,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 136,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 137,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 138,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 139,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 140,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 141,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 142,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 143,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 144,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 145,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 146,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 147,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 148,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 149,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 150,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 151,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 152,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 153,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 154,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 155,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 156,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 157,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 158,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 159,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 160,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 161,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 162,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 163,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 164,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 165,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 166,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 167,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 168,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 169,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 170,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 171,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 172,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 173,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 174,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 175,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 176,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 177,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 178,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 179,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 180,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 181,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 182,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 183,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 184,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 185,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 186,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 187,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 188,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 189,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 190,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 191,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 192,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 193,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 194,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 195,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 196,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 197,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 198,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 199,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 200,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 201,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 202,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 203,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 204,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 205,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 206,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 207,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 208,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 209,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 210,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 211,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 212,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 213,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 214,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 215,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 216,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 217,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 218,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 219,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 220,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 221,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 222,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 223,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 224,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 225,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 226,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 227,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 228,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 229,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 230,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 231,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 232,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 233,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 234,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 235,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 236,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 237,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 238,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 239,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 240,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 241,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 242,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 243,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 244,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 245,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 246,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 247,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 248,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 249,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 250,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 251,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 252,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 253,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 254,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 255,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 256,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 257,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 258,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 259,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 260,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 261,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 262,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 263,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 264,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 265,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 266,
      "dual": 444.94,
      "primal": 453.39
    },
    {
      "nodes": 267,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 268,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 269,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 270,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 271,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 272,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 273,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 274,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 275,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 276,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 277,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 278,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 279,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 280,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 281,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 282,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 283,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 284,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 285,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 286,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 287,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 288,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 289,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 290,
      "dual": 445.08,
      "primal": 453.39
    },
    {
      "nodes": 291,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 292,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 293,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 294,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 295,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 296,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 297,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 298,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 299,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 300,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 301,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 302,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 303,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 304,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 305,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 306,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 307,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 308,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 309,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 310,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 311,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 312,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 313,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 314,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 315,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 316,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 317,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 318,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 319,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 320,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 321,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 322,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 323,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 324,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 325,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 326,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 327,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 328,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 329,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 330,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 331,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 332,
      "dual": 445.13,
      "primal": 453.39
    },
    {
      "nodes": 332,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 333,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 334,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 335,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 336,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 337,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 338,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 339,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 340,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 341,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 342,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 343,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 344,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 345,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 346,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 347,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 348,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 349,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 350,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 351,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 352,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 353,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 354,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 355,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 356,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 357,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 358,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 359,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 360,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 361,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 362,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 363,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 364,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 365,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 366,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 367,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 368,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 369,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 370,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 371,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 372,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 373,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 374,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 375,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 376,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 377,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 378,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 379,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 380,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 381,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 382,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 383,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 384,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 385,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 386,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 387,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 388,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 389,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 390,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 391,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 392,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 393,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 394,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 395,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 396,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 397,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 398,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 399,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 400,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 401,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 402,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 403,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 404,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 405,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 406,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 407,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 408,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 409,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 410,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 411,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 412,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 413,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 414,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 415,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 416,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 417,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 418,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 419,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 420,
      "dual": 445.13,
      "primal": 452.62
    },
    {
      "nodes": 421,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 422,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 423,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 424,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 425,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 426,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 427,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 428,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 429,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 430,
      "dual": 446.03,
      "primal": 452.62
    },
    {
      "nodes": 431,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 432,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 433,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 434,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 435,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 436,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 437,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 438,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 439,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 440,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 441,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 442,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 443,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 444,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 445,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 446,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 447,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 448,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 449,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 450,
      "dual": 446.2,
      "primal": 452.62
    },
    {
      "nodes": 451,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 452,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 453,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 454,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 455,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 456,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 457,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 458,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 459,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 460,
      "dual": 446.26,
      "primal": 452.62
    },
    {
      "nodes": 461,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 462,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 463,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 464,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 465,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 466,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 467,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 468,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 469,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 470,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 471,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 472,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 473,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 474,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 475,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 476,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 477,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 478,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 479,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 480,
      "dual": 446.27,
      "primal": 452.62
    },
    {
      "nodes": 481,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 482,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 483,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 484,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 485,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 486,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 487,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 488,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 489,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 490,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 491,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 492,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 493,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 494,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 495,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 496,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 497,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 498,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 499,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 500,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 501,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 502,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 503,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 504,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 505,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 506,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 507,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 508,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 509,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 510,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 511,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 512,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 513,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 514,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 515,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 516,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 517,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 518,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 519,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 520,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 521,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 522,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 523,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 524,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 525,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 526,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 527,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 528,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 529,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 530,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 531,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 532,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 533,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 534,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 535,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 536,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 537,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 538,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 539,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 540,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 541,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 542,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 543,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 544,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 545,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 546,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 547,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 548,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 549,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 550,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 551,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 552,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 553,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 554,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 555,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 556,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 557,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 558,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 559,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 560,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 561,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 562,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 563,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 564,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 565,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 566,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 567,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 568,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 569,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 570,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 571,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 572,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 573,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 574,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 575,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 576,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 577,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 578,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 579,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 580,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 581,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 582,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 583,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 584,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 585,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 586,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 587,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 588,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 589,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 590,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 591,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 592,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 593,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 594,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 595,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 596,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 597,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 598,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 599,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 600,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 601,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 602,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 603,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 604,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 605,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 606,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 607,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 608,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 609,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 610,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 611,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 612,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 613,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 614,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 615,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 616,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 617,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 618,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 619,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 620,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 621,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 622,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 623,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 624,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 625,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 626,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 627,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 628,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 629,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 630,
      "dual": 446.28,
      "primal": 452.62
    },
    {
      "nodes": 631,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 632,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 633,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 634,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 635,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 636,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 637,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 638,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 639,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 640,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 641,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 642,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 643,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 644,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 645,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 646,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 647,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 648,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 649,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 650,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 651,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 652,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 653,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 654,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 655,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 656,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 657,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 658,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 659,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 660,
      "dual": 446.41,
      "primal": 452.62
    },
    {
      "nodes": 661,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 662,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 663,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 664,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 665,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 666,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 667,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 668,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 669,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 670,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 671,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 672,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 673,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 674,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 675,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 676,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 677,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 678,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 679,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 680,
      "dual": 446.63,
      "primal": 452.62
    },
    {
      "nodes": 681,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 682,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 683,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 684,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 685,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 686,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 687,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 688,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 689,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 690,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 691,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 692,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 693,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 694,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 695,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 696,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 697,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 698,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 699,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 700,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 701,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 702,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 703,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 704,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 705,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 706,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 707,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 708,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 709,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 710,
      "dual": 446.82,
      "primal": 452.62
    },
    {
      "nodes": 711,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 712,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 713,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 714,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 715,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 716,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 717,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 718,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 719,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 720,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 721,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 722,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 723,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 724,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 725,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 726,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 727,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 728,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 729,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 730,
      "dual": 447.13,
      "primal": 452.62
    },
    {
      "nodes": 731,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 732,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 733,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 734,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 735,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 736,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 737,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 738,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 739,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 740,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 741,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 742,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 743,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 744,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 745,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 746,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 747,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 748,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 749,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 750,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 751,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 752,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 753,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 754,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 755,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 756,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 757,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 758,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 759,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 760,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 761,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 762,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 763,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 764,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 765,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 766,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 767,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 768,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 769,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 770,
      "dual": 447.16,
      "primal": 452.62
    },
    {
      "nodes": 771,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 772,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 773,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 774,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 775,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 776,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 777,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 778,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 779,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 780,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 781,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 782,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 783,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 784,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 785,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 786,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 787,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 788,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 789,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 790,
      "dual": 447.45,
      "primal": 452.62
    },
    {
      "nodes": 791,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 792,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 793,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 794,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 795,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 796,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 797,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 798,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 799,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 800,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 801,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 802,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 803,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 804,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 805,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 806,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 807,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 808,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 809,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 810,
      "dual": 447.61,
      "primal": 452.62
    },
    {
      "nodes": 811,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 812,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 813,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 814,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 815,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 816,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 817,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 818,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 819,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 820,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 821,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 822,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 823,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 824,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 825,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 826,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 827,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 828,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 829,
      "dual": 447.95,
      "primal": 452.62
    },
    {
      "nodes": 830,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 831,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 832,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 833,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 834,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 835,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 836,
      "dual": 449.33,
      "primal": 452.62
    },
    {
      "nodes": 837,
      "dual": 449.65,
      "primal": 452.62
    },
    {
      "nodes": 838,
      "dual": 449.65,
      "primal": 452.62
    },
    {
      "nodes": 839,
      "dual": 450.99,
      "primal": 452.62
    },
    {
      "nodes": 840,
      "dual": 450.99,
      "primal": 452.62
    },
    {
      "nodes": 841,
      "dual": 450.99,
      "primal": 452.62
    },
    {
      "nodes": 842,
      "dual": 450.99,
      "primal": 452.62
    },
    {
      "nodes": 843,
      "dual": 452.62,
      "primal": 452.62
    }
  ],
  "meta": {
    "stops": 48,
    "variables": 2304,
    "binaries": 2256,
    "optimum": 452.62,
    "nodes": 843,
    "status": "optimal",
    "solver": "SCIP"
  }
} as const;
