// AUTO-GENERATED by scripts/gen_landing_infeasible.py — do not edit by hand.
//
// A genuinely infeasible instance, reduced to its irreducible infeasible set by
// the same deletion filtering the product uses. Every rule below was tested by
// re-solving without it.
//
// Regenerate with: python scripts/gen_landing_infeasible.py

export interface InfeasibleRule {
  readonly key: string;
  readonly operator: string;
  readonly rhs: number;
  readonly coefficient: number;
  /** Units of the product this rule alone would permit. */
  readonly allows: number;
  /** Whether the rule belongs to the irreducible infeasible set. */
  readonly inConflict: boolean;
}

export interface InfeasibleShowcase {
  readonly demand: number;
  readonly rules: readonly InfeasibleRule[];
  readonly conflict: readonly string[];
  readonly shortfall: {
    readonly resource: string;
    readonly missing: number;
    readonly reaches: number;
  };
  readonly meta: {
    readonly totalRules: number;
    readonly conflictSize: number;
    readonly clearedCount: number;
    readonly method: string;
    readonly solver: string;
  };
}

export const INFEASIBLE_SHOWCASE: InfeasibleShowcase = {
  "demand": 6000,
  "rules": [
    {
      "key": "inverterContract",
      "operator": ">=",
      "rhs": 6000,
      "coefficient": 1,
      "allows": 6000,
      "inConflict": true
    },
    {
      "key": "smtHours",
      "operator": "<=",
      "rhs": 38500,
      "coefficient": 5,
      "allows": 7700,
      "inConflict": false
    },
    {
      "key": "burnInHours",
      "operator": "<=",
      "rhs": 52400,
      "coefficient": 10,
      "allows": 5240,
      "inConflict": true
    },
    {
      "key": "mcuChips",
      "operator": "<=",
      "rhs": 94800,
      "coefficient": 12,
      "allows": 7900,
      "inConflict": false
    },
    {
      "key": "sicModules",
      "operator": "<=",
      "rhs": 158400,
      "coefficient": 24,
      "allows": 6600,
      "inConflict": false
    },
    {
      "key": "testHours",
      "operator": "<=",
      "rhs": 27600,
      "coefficient": 4,
      "allows": 6900,
      "inConflict": false
    },
    {
      "key": "coatingHours",
      "operator": "<=",
      "rhs": 19800,
      "coefficient": 3,
      "allows": 6600,
      "inConflict": false
    }
  ],
  "conflict": [
    "inverterContract",
    "burnInHours"
  ],
  "shortfall": {
    "resource": "burnInHours",
    "missing": 7600,
    "reaches": 5240
  },
  "meta": {
    "totalRules": 7,
    "conflictSize": 2,
    "clearedCount": 5,
    "method": "deletion filtering",
    "solver": "SCIP"
  }
} as const;
