// AUTO-GENERATED by scripts/gen_landing_infeasible.py — do not edit by hand.
//
// A genuinely infeasible instance, reduced to its irreducible infeasible set by
// the same deletion filtering the product uses. Every rule below was tested by
// re-solving without it.
//
// Regenerate with: python scripts/gen_landing_infeasible.py

export interface InfeasibleRule {
  readonly key: string;
  readonly operator: string;
  readonly rhs: number;
  readonly coefficient: number;
  /** Units of the product this rule alone would permit. */
  readonly allows: number;
  /** Whether the rule belongs to the irreducible infeasible set. */
  readonly inConflict: boolean;
}

export interface InfeasibleShowcase {
  readonly demand: number;
  readonly rules: readonly InfeasibleRule[];
  readonly conflict: readonly string[];
  readonly shortfall: {
    readonly resource: string;
    readonly missing: number;
    readonly reaches: number;
  };
  readonly meta: {
    readonly totalRules: number;
    readonly conflictSize: number;
    readonly method: string;
    readonly solver: string;
  };
}

export const INFEASIBLE_SHOWCASE: InfeasibleShowcase = {
  "demand": 100,
  "rules": [
    {
      "key": "chairContract",
      "operator": ">=",
      "rhs": 100,
      "coefficient": 1,
      "allows": 100,
      "inConflict": true
    },
    {
      "key": "craftHours",
      "operator": "<=",
      "rhs": 300,
      "coefficient": 3,
      "allows": 100,
      "inConflict": false
    },
    {
      "key": "oakPlanks",
      "operator": "<=",
      "rhs": 348,
      "coefficient": 4,
      "allows": 87,
      "inConflict": true
    },
    {
      "key": "machineHours",
      "operator": "<=",
      "rhs": 400,
      "coefficient": 2,
      "allows": 200,
      "inConflict": false
    }
  ],
  "conflict": [
    "chairContract",
    "oakPlanks"
  ],
  "shortfall": {
    "resource": "oakPlanks",
    "missing": 52,
    "reaches": 87
  },
  "meta": {
    "totalRules": 4,
    "conflictSize": 2,
    "method": "deletion filtering",
    "solver": "SCIP"
  }
} as const;
