// AUTO-GENERATED by scripts/gen_landing_jmodel.py — do not edit by hand.
//
// Produced by JAOT's own JModel compiler: `latexify` for the symbolic notation
// (rendered before grounding, which is why the sums and ∀ survive) and
// `compile_jmodel` for the grounded sizes. The two entries in `scales` are the
// SAME source compiled against datasets two orders of magnitude apart.
//
// Regenerate with: python scripts/gen_landing_jmodel.py

export interface JModelLine {
  readonly latex: string;
  readonly label: string | null;
}

export interface JModelScale {
  readonly products: number;
  readonly resources: number;
  readonly weeks: number;
  readonly variables: number;
  readonly constraints: number;
}

export interface JModelShowcase {
  /** The DSL source, one entry per line (blank lines included). */
  readonly source: readonly string[];
  readonly sourceLines: number;
  readonly objective: JModelLine | null;
  readonly constraints: readonly JModelLine[];
  readonly variables: readonly JModelLine[];
  readonly scales: readonly JModelScale[];
}

export const JMODEL_SHOWCASE: JModelShowcase = {
  "source": [
    "set PRODUCTS;",
    "set RESOURCES;",
    "set WEEKS;",
    "",
    "param margin{PRODUCTS};",
    "param usage{RESOURCES, PRODUCTS};",
    "param capacity{RESOURCES, WEEKS};",
    "param ceiling{PRODUCTS, WEEKS};",
    "",
    "var build{PRODUCTS, WEEKS} integer >= 0;",
    "",
    "maximize contribution:",
    "  sum{p in PRODUCTS, w in WEEKS} margin[p] * build[p, w];",
    "",
    "subject to plant{r in RESOURCES, w in WEEKS}:",
    "  sum{p in PRODUCTS} usage[r, p] * build[p, w] <= capacity[r, w];",
    "",
    "subject to market{p in PRODUCTS, w in WEEKS}:",
    "  build[p, w] <= ceiling[p, w];"
  ],
  "sourceLines": 14,
  "objective": {
    "latex": "\\max \\quad \\sum_{p \\in \\mathrm{PRODUCTS},\\; w \\in \\mathrm{WEEKS}} \\mathrm{margin}_{p} \\, \\mathrm{build}_{p,w}",
    "label": "contribution"
  },
  "constraints": [
    {
      "latex": "\\sum_{p \\in \\mathrm{PRODUCTS}} \\mathrm{usage}_{r,p} \\, \\mathrm{build}_{p,w} \\le \\mathrm{capacity}_{r,w} \\quad \\forall\\, r \\in \\mathrm{RESOURCES},\\; w \\in \\mathrm{WEEKS}",
      "label": "plant"
    },
    {
      "latex": "\\mathrm{build}_{p,w} \\le \\mathrm{ceiling}_{p,w} \\quad \\forall\\, p \\in \\mathrm{PRODUCTS},\\; w \\in \\mathrm{WEEKS}",
      "label": "market"
    }
  ],
  "variables": [
    {
      "latex": "\\mathrm{build}_{p,w} \\in \\mathbb{Z},\\; \\mathrm{build}_{p,w} \\ge 0 \\quad \\forall\\, p \\in \\mathrm{PRODUCTS},\\; w \\in \\mathrm{WEEKS}",
      "label": "build"
    }
  ],
  "scales": [
    {
      "products": 7,
      "resources": 6,
      "weeks": 13,
      "variables": 91,
      "constraints": 169
    },
    {
      "products": 400,
      "resources": 40,
      "weeks": 52,
      "variables": 20800,
      "constraints": 22880
    }
  ]
} as const;
