// AUTO-GENERATED by scripts/gen_landing_jmodel.py — do not edit by hand.
//
// Produced by JAOT's own JModel compiler: `latexify` for the symbolic notation
// (rendered before grounding, which is why the sums and ∀ survive) and
// `compile_jmodel` for the grounded sizes. The two entries in `scales` are the
// SAME source compiled against datasets two orders of magnitude apart.
//
// Regenerate with: python scripts/gen_landing_jmodel.py

export interface JModelLine {
  readonly latex: string;
  readonly label: string | null;
}

export interface JModelScale {
  readonly products: number;
  readonly resources: number;
  readonly variables: number;
  readonly constraints: number;
}

export interface JModelShowcase {
  /** The DSL source, one entry per line (blank lines included). */
  readonly source: readonly string[];
  readonly sourceLines: number;
  readonly objective: JModelLine | null;
  readonly constraints: readonly JModelLine[];
  readonly variables: readonly JModelLine[];
  readonly scales: readonly JModelScale[];
}

export const JMODEL_SHOWCASE: JModelShowcase = {
  "source": [
    "set PRODUCTS;",
    "set RESOURCES;",
    "",
    "param margin{PRODUCTS};",
    "param usage{RESOURCES, PRODUCTS};",
    "param capacity{RESOURCES};",
    "",
    "var make{PRODUCTS} integer >= 0;",
    "",
    "maximize profit: sum{p in PRODUCTS} margin[p] * make[p];",
    "",
    "subject to cap{r in RESOURCES}:",
    "  sum{p in PRODUCTS} usage[r, p] * make[p] <= capacity[r];"
  ],
  "sourceLines": 9,
  "objective": {
    "latex": "\\max \\quad \\sum_{p \\in \\mathrm{PRODUCTS}} \\mathrm{margin}_{p} \\, \\mathrm{make}_{p}",
    "label": "profit"
  },
  "constraints": [
    {
      "latex": "\\sum_{p \\in \\mathrm{PRODUCTS}} \\mathrm{usage}_{r,p} \\, \\mathrm{make}_{p} \\le \\mathrm{capacity}_{r} \\quad \\forall\\, r \\in \\mathrm{RESOURCES}",
      "label": "cap"
    }
  ],
  "variables": [
    {
      "latex": "\\mathrm{make}_{p} \\in \\mathbb{Z},\\; \\mathrm{make}_{p} \\ge 0 \\quad \\forall\\, p \\in \\mathrm{PRODUCTS}",
      "label": "make"
    }
  ],
  "scales": [
    {
      "products": 4,
      "resources": 3,
      "variables": 4,
      "constraints": 3
    },
    {
      "products": 400,
      "resources": 30,
      "variables": 400,
      "constraints": 30
    }
  ]
} as const;
