"""Generate the landing page's template-catalogue summary from the real YAML.

The home page used to advertise six hand-picked use cases. The actual catalogue
is far more convincing and, unlike a curated list, it cannot drift: this reads
app/data/templates/*.yaml and emits the sectors with their real counts, so
adding or retiring a template updates the page on the next run.

    python scripts/gen_landing_catalog.py

Output: frontend/src/components/landing/data/catalogSummary.ts
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "app" / "data" / "templates"
OUTPUT = ROOT / "frontend" / "src" / "components" / "landing" / "data" / "catalogSummary.ts"


def collect() -> dict:
    sectors: list[dict] = []
    total = 0
    featured: list[dict] = []

    for path in sorted(TEMPLATES.glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or "templates" not in data:
            continue

        templates = data["templates"]
        if not templates:
            continue

        display = data.get("category_display_name") or data.get("category") or path.stem
        sectors.append({"name": str(display), "count": len(templates)})
        total += len(templates)

        for template in templates:
            if template.get("is_featured"):
                featured.append(
                    {
                        "name": str(template.get("display_name") or template.get("name")),
                        "sector": str(display),
                        "variables": template.get("estimated_variables"),
                    }
                )

    sectors.sort(key=lambda s: (-s["count"], s["name"]))
    # Biggest instances first: they make the point that this is not toy scale.
    featured.sort(key=lambda f: -(f["variables"] or 0))

    return {
        "total": total,
        "sectors": sectors,
        "featured": featured[:6],
        "meta": {"sectorCount": len(sectors), "files": len(sectors)},
    }


def emit(data: dict) -> str:
    header = """// AUTO-GENERATED by scripts/gen_landing_catalog.py — do not edit by hand.
//
// Counted from app/data/templates/*.yaml, so the figures on the home page are
// the catalogue itself rather than a claim about it.
//
// Regenerate with: python scripts/gen_landing_catalog.py

export interface CatalogSector {
  readonly name: string;
  readonly count: number;
}

export interface CatalogFeatured {
  readonly name: string;
  readonly sector: string;
  readonly variables: number | null;
}

export interface CatalogSummary {
  readonly total: number;
  readonly sectors: readonly CatalogSector[];
  readonly featured: readonly CatalogFeatured[];
  readonly meta: {
    readonly sectorCount: number;
    readonly files: number;
  };
}

export const CATALOG_SUMMARY: CatalogSummary = """
    return header + json.dumps(data, indent=2) + " as const;\n"


def main() -> None:
    data = collect()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(emit(data), encoding="utf-8")

    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    print(f"  {data['total']} templates across {data['meta']['sectorCount']} sectors")
    for sector in data["sectors"][:8]:
        print(f"    {sector['name']:34s} {sector['count']:3d}")
    print(f"  featured shown: {len(data['featured'])}")


if __name__ == "__main__":
    main()
