"""Generate the landing page's JModel showcase with the real compiler.

JModel is not an optional extra — it is the product (the JAOT_DSL flag was
retired for exactly that reason), and the home page did not show it at all.

This runs the real compiler twice on the SAME source:
- `latexify` renders the model symbolically, BEFORE grounding, which is why the
  sums and the ∀ survive instead of flattening into thousands of scalar rows;
- `compile_jmodel` then grounds it against two datasets of very different sizes.

The second part is the argument: the source does not change when the data grows
by two orders of magnitude. That is what separates writing a model from writing
out a model.

    python scripts/gen_landing_jmodel.py

Output: frontend/src/components/landing/data/jmodelShowcase.ts
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Run from anywhere: this imports the real compiler out of the backend package,
# which is not on the path when the script is invoked from scripts/.
sys.path.insert(0, str(ROOT))

from app.domains.dsl.compiler import JModelData, compile_jmodel, latexify  # noqa: E402

OUTPUT = ROOT / "frontend" / "src" / "components" / "landing" / "data" / "jmodelShowcase.ts"

# The plant the rest of the page solves, written the way JModel is meant to be
# written — and extended over a planning horizon, which is where hand-written
# models fall apart. A week is just another index; the source does not notice.
SOURCE = """set PRODUCTS;
set RESOURCES;
set WEEKS;

param margin{PRODUCTS};
param usage{RESOURCES, PRODUCTS};
param capacity{RESOURCES, WEEKS};
param ceiling{PRODUCTS, WEEKS};

var build{PRODUCTS, WEEKS} integer >= 0;

maximize contribution:
  sum{p in PRODUCTS, w in WEEKS} margin[p] * build[p, w];

subject to plant{r in RESOURCES, w in WEEKS}:
  sum{p in PRODUCTS} usage[r, p] * build[p, w] <= capacity[r, w];

subject to market{p in PRODUCTS, w in WEEKS}:
  build[p, w] <= ceiling[p, w];
"""

# The plant on this page, week by week — and then a group of them for a year.
SMALL = (7, 6, 13)
LARGE = (400, 40, 52)


def dataset(products: int, resources: int, weeks: int) -> JModelData:
    """A synthetic instance of the given shape. Only the SIZE matters here."""
    prods = [f"p{i}" for i in range(products)]
    res = [f"r{j}" for j in range(resources)]
    horizon = [f"w{k}" for k in range(weeks)]
    return JModelData.from_json(
        {
            "sets": {"PRODUCTS": prods, "RESOURCES": res, "WEEKS": horizon},
            "params": {
                "margin": {p: 260 + (i % 2200) for i, p in enumerate(prods)},
                "capacity": {
                    f"{r},{w}": 30000 + 700 * j for j, r in enumerate(res) for w in horizon
                },
                "ceiling": {f"{p},{w}": 900 for p in prods for w in horizon},
                "usage": {
                    f"{r},{p}": 1 + ((i + j) % 12)
                    for j, r in enumerate(res)
                    for i, p in enumerate(prods)
                },
            },
        }
    )


def measure(products: int, resources: int, weeks: int) -> dict:
    problem = compile_jmodel(SOURCE, data=dataset(products, resources, weeks))
    return {
        "products": products,
        "resources": resources,
        "weeks": weeks,
        "variables": len(problem.variables),
        "constraints": len(problem.constraints),
    }


def build() -> dict:
    rendered = latexify(SOURCE)

    lines = [ln.rstrip() for ln in SOURCE.strip().split("\n")]
    return {
        "source": lines,
        "sourceLines": len([ln for ln in lines if ln.strip()]),
        "objective": (
            {"latex": rendered.objective.latex, "label": rendered.objective.label}
            if rendered.objective
            else None
        ),
        "constraints": [{"latex": c.latex, "label": c.label} for c in rendered.constraints],
        "variables": [{"latex": v.latex, "label": v.label} for v in rendered.variables],
        # Same source, two orders of magnitude apart.
        "scales": [measure(*SMALL), measure(*LARGE)],
    }


def emit(data: dict) -> str:
    header = """// AUTO-GENERATED by scripts/gen_landing_jmodel.py — do not edit by hand.
//
// Produced by JAOT's own JModel compiler: `latexify` for the symbolic notation
// (rendered before grounding, which is why the sums and ∀ survive) and
// `compile_jmodel` for the grounded sizes. The two entries in `scales` are the
// SAME source compiled against datasets two orders of magnitude apart.
//
// Regenerate with: python scripts/gen_landing_jmodel.py

export interface JModelLine {
  readonly latex: string;
  readonly label: string | null;
}

export interface JModelScale {
  readonly products: number;
  readonly resources: number;
  readonly weeks: number;
  readonly variables: number;
  readonly constraints: number;
}

export interface JModelShowcase {
  /** The DSL source, one entry per line (blank lines included). */
  readonly source: readonly string[];
  readonly sourceLines: number;
  readonly objective: JModelLine | null;
  readonly constraints: readonly JModelLine[];
  readonly variables: readonly JModelLine[];
  readonly scales: readonly JModelScale[];
}

export const JMODEL_SHOWCASE: JModelShowcase = """
    return header + json.dumps(data, indent=2, ensure_ascii=False) + " as const;\n"


def main() -> None:
    data = build()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(emit(data), encoding="utf-8")

    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    print(f"  {data['sourceLines']} non-blank lines of JModel")
    for scale in data["scales"]:
        print(
            f"  {scale['products']:4d} products x {scale['resources']:3d} resources "
            f"x {scale['weeks']:3d} weeks -> {scale['variables']:6d} variables, "
            f"{scale['constraints']:6d} constraints"
        )


if __name__ == "__main__":
    main()
