"""Generate the landing page's infeasibility showcase with the real solver.

When a model has no answer, a solver says "infeasible" and stops. JAOT finds an
Irreducible Infeasible Set: a minimal group of rules that contradict each other,
where dropping any one of them makes the model solvable again. This script
reproduces that with the same method the product uses — deletion filtering, one
feasibility re-solve per removable constraint, objective replaced by the constant
0 so a candidate can only come back feasible or infeasible, never unbounded
(app/domains/solver/services/infeasibility.py).

Same furniture workshop as the analysis section, so the page tells one story.
The instance is written out by hand and the search is exhaustive, so the result
is deterministic.

    python scripts/gen_landing_infeasible.py

Output: frontend/src/components/landing/data/infeasibleShowcase.ts
"""

from __future__ import annotations

import json
from pathlib import Path

from pyscipopt import Model

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "frontend"
    / "src"
    / "components"
    / "landing"
    / "data"
    / "infeasibleShowcase.ts"
)

# One product, four rules. The contract demands 100 chairs; oak planks only
# stretch to 87. Craft hours and machine hours are innocent — they would cover
# 100 chairs comfortably — and the point of the section is that JAOT says so
# instead of blaming the whole model.
DEMAND = 100
RULES = [
    {"key": "chairContract", "coefficient": 1, "operator": ">=", "rhs": DEMAND},
    {"key": "craftHours", "coefficient": 3, "operator": "<=", "rhs": 300},
    {"key": "oakPlanks", "coefficient": 4, "operator": "<=", "rhs": 348},
    {"key": "machineHours", "coefficient": 2, "operator": "<=", "rhs": 400},
]


def is_feasible(active: list[dict]) -> bool:
    """Solve a pure feasibility problem over the given rules."""
    model = Model("feasibility")
    model.hideOutput()
    chairs = model.addVar(vtype="I", lb=0, name="chairs")
    for rule in active:
        if rule["operator"] == ">=":
            model.addCons(rule["coefficient"] * chairs >= rule["rhs"])
        else:
            model.addCons(rule["coefficient"] * chairs <= rule["rhs"])
    # Constant objective: the answer can only be feasible or infeasible.
    model.setObjective(0)
    model.optimize()
    return model.getStatus() != "infeasible"


def deletion_filter() -> list[str]:
    """Deletion filtering, as the product does it: tentatively drop each rule and
    keep it only if the model becomes feasible without it."""
    required = list(RULES)
    for rule in list(required):
        candidate = [r for r in required if r["key"] != rule["key"]]
        if not is_feasible(candidate):
            # Still contradictory without it — the rule was not part of the clash.
            required = candidate
    return [r["key"] for r in required]


def build() -> dict:
    assert not is_feasible(RULES), "the showcase instance must be infeasible"

    conflict = deletion_filter()
    assert is_feasible([r for r in RULES if r["key"] != conflict[0]]), (
        "dropping a member of the conflict must restore feasibility"
    )

    rows = []
    for rule in RULES:
        # What this rule alone would allow, in units of the product.
        limit = rule["rhs"] / rule["coefficient"]
        rows.append(
            {
                "key": rule["key"],
                "operator": rule["operator"],
                "rhs": rule["rhs"],
                "coefficient": rule["coefficient"],
                "allows": int(limit) if rule["operator"] == "<=" else int(limit),
                "inConflict": rule["key"] in conflict,
            }
        )

    # The actionable number: how much more of the binding resource the demand needs.
    tightest = min(
        (r for r in rows if r["inConflict"] and r["operator"] == "<="),
        key=lambda r: r["allows"],
    )
    shortfall = DEMAND * tightest["coefficient"] - tightest["rhs"]

    return {
        "demand": DEMAND,
        "rules": rows,
        "conflict": conflict,
        "shortfall": {
            "resource": tightest["key"],
            "missing": shortfall,
            "reaches": tightest["allows"],
        },
        "meta": {
            "totalRules": len(RULES),
            "conflictSize": len(conflict),
            "method": "deletion filtering",
            "solver": "SCIP",
        },
    }


def emit(data: dict) -> str:
    header = """// AUTO-GENERATED by scripts/gen_landing_infeasible.py — do not edit by hand.
//
// A genuinely infeasible instance, reduced to its irreducible infeasible set by
// the same deletion filtering the product uses. Every rule below was tested by
// re-solving without it.
//
// Regenerate with: python scripts/gen_landing_infeasible.py

export interface InfeasibleRule {
  readonly key: string;
  readonly operator: string;
  readonly rhs: number;
  readonly coefficient: number;
  /** Units of the product this rule alone would permit. */
  readonly allows: number;
  /** Whether the rule belongs to the irreducible infeasible set. */
  readonly inConflict: boolean;
}

export interface InfeasibleShowcase {
  readonly demand: number;
  readonly rules: readonly InfeasibleRule[];
  readonly conflict: readonly string[];
  readonly shortfall: {
    readonly resource: string;
    readonly missing: number;
    readonly reaches: number;
  };
  readonly meta: {
    readonly totalRules: number;
    readonly conflictSize: number;
    readonly method: string;
    readonly solver: string;
  };
}

export const INFEASIBLE_SHOWCASE: InfeasibleShowcase = """
    return header + json.dumps(data, indent=2) + " as const;\n"


def main() -> None:
    data = build()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(emit(data), encoding="utf-8")

    print(f"Wrote {OUTPUT.relative_to(Path(__file__).resolve().parent.parent)}")
    print(f"  demand={data['demand']}  conflict={data['conflict']}")
    for r in data["rules"]:
        mark = "CONFLICT" if r["inConflict"] else "innocent"
        print(
            f"  {r['key']:16s} {r['coefficient']}x {r['operator']} {r['rhs']:5d} "
            f"-> allows {r['allows']:4d}   {mark}"
        )
    s = data["shortfall"]
    print(f"  shortfall: {s['missing']} more {s['resource']} (reaches {s['reaches']})")


if __name__ == "__main__":
    main()
