// Imported so they can be referenced by frontend-only types below; re-exported alongside the barrels.
import type {
  OptimizationProblemInput as _OptimizationProblem,
  OptimizationResult as _OptimizationResult,
  OverrideFieldSchema as _OverrideField,
  PlanLimitsResponse as _PlanLimits,
  SkillLevel as _SkillLevel,
  SolverStatus as _SolverStatus,
} from "./generated/api";

// Generated by openapi-typescript from the FastAPI backend — do not edit generated file directly.
export type {
  ObjectiveSense,
  SkillLevel,
  SolverStatus,
  VariableType,
} from "./generated/api";

export type {
  Constraint,
  ConstraintSensitivity,
  MultiObjectiveConfig,
  MultiObjectiveResult,
  Objective,
  ObjectiveSpec,
  OptimizationProblemInput as OptimizationProblem,
  OptimizationResult,
  ParetoPoint,
  SensitivityResult,
  SolverOptions,
  Variable,
  VariableSolution,
  WarmStartConfig,
} from "./generated/api";

export type {
  PlanLimitsResponse as PlanLimits,
} from "./generated/api";

export type {
  CreateKeyResponse,
} from "./generated/api";

export type {
  BuilderDocumentUpdate,
} from "./generated/api";

export type {
  ModelVersionListItem,
  ModelVersionResponse as ModelVersion,
} from "./generated/api";

export type {
  OverrideFieldSchema as OverrideField,
  ScheduleCreateRequest,
  ScheduleUpdateRequest,
  CronValidationResponse,
} from "./generated/api";

export type {
  GuidanceUpdate,
} from "./generated/api";

export type {
  CreditPoolResponse as CreditPool,
} from "./generated/api";

// Frontend-only types live below. Some have backend counterparts with slightly different shapes;
// kept here until the API types converge and these can be replaced with generated re-exports.
// Union literal types are not separate schemas in the OpenAPI spec (backend uses plain `str`).

export type Plan = "free" | "starter" | "pro" | "business" | "unlimited";
export type Currency = "EUR" | "USD" | "GBP" | "CHF";
export type ModelCategory =
  | "linear"
  | "integer"
  | "mixed_integer"
  | "nonlinear"
  | "quadratic"
  | "network"
  | "scheduling"
  | "routing"
  | "assignment"
  | "other";
export type ExecutionStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timeout";
export type TransactionType =
  | "signup_bonus"
  | "monthly_grant"
  | "admin_adjustment"
  | "execution_charge"
  | "execution_refund"
  | "publisher_earning"
  | "withdrawal";
export type WithdrawalStatus = "pending" | "processing" | "completed" | "failed" | "cancelled";
export type NotificationType =
  | "execution_completed"
  | "execution_failed"
  | "credits_low"
  | "model_published"
  | "system_announcement";
export type TriggerRunStatus =
  | "pending" | "running" | "completed" | "failed" | "timeout" | "validation_failed"
  | "skipped_credits" | "skipped_overlap";
export type WorkspaceRole = "viewer" | "solver" | "editor" | "admin";

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}

// LoginResult and UserInfo have different structure from generated LoginResponse/MeResponse
// (generated types use loose `string` for enum fields and `Record<string, unknown>` for nested objects).

export interface LoginResult {
  success: boolean;
  user: {
    id: string;
    name: string;
    email: string;
    is_admin: boolean;
    is_org_owner?: boolean;
  };
  organization: {
    id: string;
    name: string;
    plan: Plan;
  };
  permissions: {
    can_build_plugins: boolean;
    can_publish: boolean;
    can_manage_keys: boolean;
  };
}

export interface UserInfo {
  user_id: string;
  user_name: string;
  user_email?: string;
  organization_id: string;
  organization_name: string;
  plan: Plan;
  credits_balance: number;
  is_admin: boolean;
  is_org_owner?: boolean;
  can_build_plugins: boolean;
  plan_limits?: _PlanLimits;
}

// Generated OrganizationResponse has different fields (ai_builder_enabled, rate limits, etc.)

export interface Organization {
  id: string;
  name: string;
  slug: string;
  description?: string;
  website?: string;
  plan: Plan;
  is_active: boolean;
  is_verified: boolean;
  credits_balance: number;
  credits_earned: number;
  credits_used_month: number;
  total_users: number;
  total_models: number;
  total_executions: number;
  created_at: string;
  updated_at: string;
}

export interface OrgProfile {
  id: string;
  name: string;
  slug: string;
  bio?: string;
  logo_url?: string;
  website_url?: string;
  linkedin_url?: string;
  twitter_url?: string;
  is_verified: boolean;
  created_at: string;
  total_models_published: number;
  total_activations: number;
  total_executions: number;
  total_reviews: number;
  avg_rating: number | null;
}

// Generated UserResponse doesn't have last_login; UserPublicProfile has nullable slug

export interface User {
  id: string;
  email: string;
  name: string;
  organization_id: string;
  is_admin: boolean;
  is_active: boolean;
  created_at: string;
  last_login?: string;
}

export interface UserProfile {
  id: string;
  name: string;
  display_name?: string;
  slug: string;
  bio?: string;
  avatar_url?: string;
  linkedin_url?: string;
  twitter_url?: string;
  organization_id: string;
  organization_name: string;
  organization_verified: boolean;
  total_reviews: number;
  avg_rating_given: number;
}

// Generated ApiKeyInfo has different fields from frontend APIKey

export interface APIKey {
  id: string;
  name: string;
  key_prefix: string;
  description?: string;
  is_active: boolean;
  created_at: string;
  last_used_at?: string;
  expires_at?: string;
}

// Generated ModelCatalogResponse uses `string` for category instead of ModelCategory enum

export interface ModelCatalogItem {
  id: string;
  name: string;
  display_name: string;
  description?: string;
  short_description?: string;
  category: ModelCategory;
  tags: string[];
  version: string;
  is_official: boolean;
  is_featured: boolean;
  price_eur: number;
  credits_per_execution: number;
  total_activations: number;
  total_executions: number;
  avg_execution_time_ms?: number;
  success_rate?: number;
  avg_rating?: number;
  author_organization_id: string;
  author_name: string;
  author_verified: boolean;
  logo_url?: string | null;
  screenshot_urls?: string[] | null;
  section_overview?: string | null;
  section_features?: string | null;
  section_how_it_works?: string | null;
  section_example_io?: string | null;
  section_changelog?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OrganizationModel {
  id: string;
  organization_id: string;
  catalog_id?: string;
  custom_name?: string;
  display_name: string;
  description?: string;
  category: ModelCategory;
  is_active: boolean;
  is_favorite: boolean;
  total_executions: number;
  total_credits_used: number;
  last_executed_at?: string;
  credits_per_execution: number;
  created_at: string;
}

export interface FileImportMetadata {
  source_format: string;
  num_variables: number;
  num_constraints: number;
  num_integer: number;
  num_binary: number;
  num_continuous: number;
  estimated_credits: number;
  file_size_bytes: number;
  original_filename: string;
}

export interface FileImportPreviewResponse {
  problem: _OptimizationProblem;
  metadata: FileImportMetadata;
}

// Generated ModelExecutionResponse uses loose `string` for status/solver_status
// and `Record<string, unknown>` for result_data instead of OptimizationResult.

export interface ModelExecution {
  id: string;
  organization_model_id: string | null;
  status: ExecutionStatus;
  input_data?: Record<string, unknown>;
  result_data?: _OptimizationResult;
  error_message?: string;
  execution_time_ms?: number;
  solver_status?: _SolverStatus;
  objective_value?: number;
  credits_consumed: number;
  created_at: string;
  completed_at?: string;
  origin?: "manual" | "triggered";
  trigger_id?: string;
  solver_name?: string;
}

export interface AsyncTask {
  task_id: string;
  status: string;
}

export interface AsyncTaskStatus {
  task_id: string;
  status: ExecutionStatus;
  result?: ModelExecution;
  error?: string;
  progress?: number;
}

// Uses intersection type since OptimizationResult is a type alias from the generated file.

export type SolveResult = _OptimizationResult & {
  execution_id: string;
};

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

// Generated CreditBalanceResponse has different fields (currency, exchange_rate, etc.)

export interface CreditBalance {
  credits_balance: number;
  credits_earned: number;
  credits_used_month: number;
  plan: Plan;
  monthly_limit?: number;
}

export interface CreditSettings {
  low_balance_threshold: number;
  auto_topup_enabled: boolean;
  auto_topup_amount?: number;
}

export interface CreditTransaction {
  id: string;
  transaction_type: TransactionType;
  credits_amount: number;
  balance_after: number;
  description: string;
  reference_type?: string;
  reference_id?: string;
  created_at: string;
}

export interface Withdrawal {
  id: string;
  credits_amount: number;
  currency: Currency;
  amount_fiat: number;
  status: WithdrawalStatus;
  created_at: string;
  processed_at?: string;
}

export interface WithdrawalSchedule {
  id: string;
  credits_amount: number;
  currency: Currency;
  frequency: string;
  next_execution: string;
  is_active: boolean;
  created_at: string;
}

export interface EarningsSummary {
  total_sales: number;
  total_earned: number;
  total_commission: number;
  withdrawable_balance: number;
  pending_withdrawals: number;
  commission_rate: number;
}

export interface SaleRecord {
  sale_id: string;
  model_id: string | null;
  model_name: string | null;
  buyer_organization_name: string | null;
  credits_price: number;
  commission_amount: number;
  seller_earning: number;
  created_at: string;
}

export interface SalesHistoryResponse {
  items: SaleRecord[];
  total: number;
  page: number;
  page_size: number;
}

export interface AnalyticsSummary {
  total_views: number;
  total_impressions: number;
  total_activations: number;
  total_revenue: number;
  conversion_rate: number;
  period: string;
}

export interface TimeSeriesDataPoint {
  date: string;
  views: number;
  impressions: number;
  activations: number;
  revenue: number;
}

export interface GeoDistributionEntry {
  country: string;
  count: number;
}

export interface ModelPerformanceRow {
  model_id: string;
  model_name: string;
  views: number;
  activations: number;
  revenue: number;
  conversion_rate: number;
}

export interface ConversionFunnel {
  impressions: number;
  views: number;
  activations: number;
}

export interface SellerLeaderboardEntry {
  org_id: string;
  org_name: string;
  total_sales: number;
  total_revenue: number;
  models_published: number;
  avg_rating: number | null;
}

export interface AdminAnalytics {
  platform_totals: AnalyticsSummary;
  sellers: SellerLeaderboardEntry[];
}

export interface PlacementPricingTier {
  duration_days: number;
  credits_cost: number;
}

export interface PlacementPricing {
  placement_type: string;
  tiers: PlacementPricingTier[];
}

export interface FeaturedPlacement {
  id: string;
  catalog_model_id: string;
  placement_type: string;
  status: string;
  credits_paid: number;
  duration_days: number;
  starts_at: string;
  expires_at: string;
  created_at: string;
}

export interface AdminPlacement extends FeaturedPlacement {
  org_name: string | null;
  model_name: string | null;
  revoked_at: string | null;
  revoked_by: string | null;
}

export interface VerificationRequestStatus {
  id: string;
  organization_id: string;
  status: string;
  admin_note: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export interface AdminVerificationEntry {
  id: string;
  organization_id: string;
  org_name: string;
  profile_completeness: number;
  models_published: number;
  member_since: string;
  status: string;
  created_at: string;
}

export interface NotificationPreferenceEntry {
  event_type: string;
  channel: string;
  enabled: boolean;
}

export interface NotificationPreferencesResponse {
  preferences: NotificationPreferenceEntry[];
}

export interface OnboardingStep {
  key: string;
  completed: boolean;
  link: string;
}

export interface OnboardingStatus {
  steps: OnboardingStep[];
  all_complete: boolean;
}

// Generated NotificationResponse uses loose `string` for type field

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  is_read: boolean;
  data?: Record<string, unknown>;
  created_at: string;
}

export interface NotificationList {
  items: Notification[];
  total: number;
  unread_count: number;
}

// Generated ReviewResponse uses optional `string | null` for fields the frontend expects non-null

export interface Review {
  id: string;
  catalog_id: string;
  user_id: string;
  user_name: string;
  organization_name: string;
  rating: number;
  title?: string;
  comment?: string;
  created_at: string;
  is_visible: boolean;
}

export interface ReviewList {
  items: Review[];
  total: number;
  avg_rating: number;
}

export interface InputField {
  name: string;
  label?: string;
  type: "string" | "number" | "integer" | "boolean" | "array" | "object";
  required?: boolean;
  default?: unknown;
  description?: string;
  minimum?: number;
  maximum?: number;
  enum?: string[];
}

export interface TemplateSummary {
  id: string;
  name: string;
  display_name: string;
  description: string;
  category: string;
  tags: string[];
}

export interface BuilderDocument {
  id: string;
  organization_id: string;
  created_by: string | null;
  name: string;
  canvas_json: Record<string, unknown>;
  model_json: Record<string, unknown> | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface BuilderDocumentListItem {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface AdminStats {
  organizations: { total: number; active: number };
  users: { total: number; active: number };
  api_keys: { total: number; active: number };
  models: { catalog_total: number; catalog_public: number; activated_total: number };
  credits: { total_balance: number };
}

export interface AdminOrganizationSummary {
  id: string;
  name: string;
  plan: string;
  credits_balance: number;
  user_count: number;
  created_at: string;
}

export interface AdminUserSummary {
  id: string;
  name: string;
  email: string;
  organization_id: string;
  role: string;
  is_active: boolean;
  created_at: string;
}

export interface AdminUser extends AdminUserSummary {
  last_login_at: string | null;
  updated_at: string;
}

export interface AdminAPIKey {
  id: string;
  name: string;
  description?: string;
  key_prefix: string;
  organization_id: string;
  user_id: string;
  is_active: boolean;
  created_at: string;
  last_used_at: string | null;
  full_key?: string;
}

// Generated TriggerResponse uses `Record<string, unknown>[]` for override_schema,
// and uses loose `string` for status/source fields.

export interface SolveTrigger {
  id: string;
  organization_id: string;
  created_by: string | null;
  name: string;
  description?: string;
  document_id: string;
  version_id: string;
  workspace_id?: string | null;
  override_schema: _OverrideField[] | null;
  webhook_url: string;
  is_enabled: boolean;
  total_runs: number;
  last_fired_at?: string;
  trigger_secret_prefix: string;
  created_at: string;
  updated_at: string;
}

export interface CreateTriggerResponse extends SolveTrigger {
  trigger_secret: string;
}

export interface TriggerRun {
  id: string;
  trigger_id: string;
  organization_id: string;
  source: "manual" | "cron" | "rerun";
  status: TriggerRunStatus;
  execution_id?: string | null;
  override_data?: Record<string, unknown>;
  result_data?: Record<string, unknown>;
  error_message?: string;
  credits_consumed: number;
  execution_time_ms?: number;
  webhook_delivered?: boolean;
  webhook_attempts: number;
  created_at: string;
  completed_at?: string;
}

export interface CreateTriggerRequest {
  name: string;
  description?: string;
  document_id: string;
  version_id: string;
  override_schema?: _OverrideField[];
  webhook_url: string;
  webhook_secret?: string;
  workspace_id?: string;
}

export interface TriggerSchedule {
  id: string;
  trigger_id: string;
  cron_expression: string;
  timezone: string;
  is_enabled: boolean;
  consecutive_failures: number;
  last_run_at: string | null;
  next_run_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface GuidanceState {
  skill_level: _SkillLevel;
  wizard_step: number;
  wizard_dismissed: boolean;
  wizard_completed: boolean;
}

// Generated WorkspaceResponse/WorkspaceMemberResponse use loose `string` for role field

export interface Workspace {
  id: string;
  name: string;
  description: string | null;
  is_active: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  member_count: number;
  pool_allocated: number | null;
  pool_used: number | null;
}

export interface WorkspaceMember {
  id: string;
  user_id: string;
  user_name: string;
  user_email: string;
  role: WorkspaceRole;
  joined_at: string;
  invited_by: string | null;
}

export interface WorkspaceInvite {
  id: string;
  workspace_id: string;
  role: WorkspaceRole;
  method: "email" | "link";
  invitee_email: string | null;
  created_at: string;
  expires_at: string;
  is_revoked: boolean;
}

export interface AuditLogEntry {
  id: string;
  workspace_id: string | null;
  actor_id: string;
  actor_name: string;
  action: string;
  target_type: string | null;
  target_id: string | null;
  target_name: string | null;
  before_state: Record<string, unknown> | null;
  after_state: Record<string, unknown> | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface SolveAnalyticsSummary {
  total_executions: number;
  completed: number;
  failed: number;
  timed_out: number;
  success_rate: number;
  avg_solve_time_ms: number | null;
  median_solve_time_ms: number | null;
  total_credits: number;
  avg_credits: number;
  avg_objective_value: number | null;
  executions_by_status: Record<string, number>;
  executions_by_origin: Record<string, number>;
  solver_status_distribution: Record<string, number>;
}

export interface TrendBucket {
  date: string;
  executions: number;
  completed: number;
  failed: number;
  credits: number;
  avg_solve_time_ms: number | null;
}

export interface SolveAnalyticsTrends {
  days: number;
  bucket: string;
  data: TrendBucket[];
}

export interface ComparedExecution {
  id: string;
  status: string;
  solver_status: string | null;
  objective_value: number | null;
  execution_time_ms: number | null;
  credits_consumed: number;
  created_at: string;
  origin: string;
  num_variables: number | null;
  num_constraints: number | null;
  gap: number | null;
}

export interface SolveAnalyticsCompare {
  executions: ComparedExecution[];
}
