// Imported so they can be referenced by frontend-only types below; re-exported alongside the barrels.
import type {
  OptimizationProblemInput as _OptimizationProblem,
  OptimizationResult as _OptimizationResult,
  OverrideFieldSchema as _OverrideField,
  PlanLimitsResponse as _PlanLimits,
  SkillLevel as _SkillLevel,
  SolverStatus as _SolverStatus,
} from "./generated/api";

// Generated by openapi-typescript from the FastAPI backend — do not edit generated file directly.
export type {
  ObjectiveSense,
  SkillLevel,
  SolverStatus,
  VariableType,
} from "./generated/api";

export type {
  Constraint,
  ConstraintSensitivity,
  ConstraintUtilization,
  ExactAnalysis,
  MultiObjectiveConfig,
  MultiObjectiveResult,
  Objective,
  ObjectiveCoeffRange,
  ObjectiveSpec,
  ObjectiveTermContribution,
  OptimizationProblemInput as OptimizationProblem,
  OptimizationResult,
  ParetoPoint,
  RhsRange,
  SensitivityResult,
  SolverOptions,
  Variable,
  VariableSensitivity,
  VariableSolution,
  WarmStartConfig,
} from "./generated/api";

export type {
  PlanLimitsResponse as PlanLimits,
} from "./generated/api";

export type {
  CreateKeyResponse,
} from "./generated/api";

export type {
  BuilderDocumentUpdate,
} from "./generated/api";

export type {
  ModelVersionListItem,
  ModelVersionResponse as ModelVersion,
} from "./generated/api";

export type {
  OverrideFieldSchema as OverrideField,
  ScheduleCreateRequest,
  ScheduleUpdateRequest,
  CronValidationResponse,
} from "./generated/api";

export type {
  GuidanceUpdate,
} from "./generated/api";

export type {
} from "./generated/api";

// Frontend-only types live below. Some have backend counterparts with slightly different shapes;
// kept here until the API types converge and these can be replaced with generated re-exports.
// Union literal types are not separate schemas in the OpenAPI spec (backend uses plain `str`).

export type Plan = "free" | "starter" | "pro" | "business" | "unlimited";
export type Currency = "EUR" | "USD" | "GBP" | "CHF";
export type ModelCategory =
  | "linear"
  | "integer"
  | "mixed_integer"
  | "nonlinear"
  | "quadratic"
  | "network"
  | "scheduling"
  | "routing"
  | "assignment"
  | "other";
export type ExecutionStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timeout";
export type NotificationType =
  | "execution_completed"
  | "execution_failed"
  | "model_published"
  | "system_announcement";
export type TriggerRunStatus =
  | "pending" | "running" | "completed" | "failed" | "timeout" | "validation_failed"
  | "skipped_overlap";
export type WorkspaceRole = "viewer" | "solver" | "editor" | "admin";

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}

// LoginResult and UserInfo have different structure from generated LoginResponse/MeResponse
// (generated types use loose `string` for enum fields and `Record<string, unknown>` for nested objects).

export interface LoginResult {
  success: boolean;
  user: {
    id: string;
    name: string;
    email: string;
    is_admin: boolean;
    is_org_owner?: boolean;
  };
  organization: {
    id: string;
    name: string;
    plan: Plan;
  };
  permissions: {
    can_build_plugins: boolean;
    can_publish: boolean;
    can_manage_keys: boolean;
  };
}

export interface UserInfo {
  user_id: string;
  user_name: string;
  user_email?: string;
  organization_id: string;
  organization_name: string;
  plan: Plan;
  is_admin: boolean;
  is_org_owner?: boolean;
  can_build_plugins: boolean;
  plan_limits?: _PlanLimits;
}

// Generated OrganizationResponse has different fields (ai_builder_enabled, rate limits, etc.)

export interface Organization {
  id: string;
  name: string;
  slug: string;
  description?: string;
  website?: string;
  plan: Plan;
  is_active: boolean;
  is_verified: boolean;
  total_users: number;
  total_models: number;
  total_executions: number;
  created_at: string;
  updated_at: string;
}

export interface OrgProfile {
  id: string;
  name: string;
  slug: string;
  bio?: string;
  logo_url?: string;
  website_url?: string;
  linkedin_url?: string;
  twitter_url?: string;
  is_verified: boolean;
  created_at: string;
  total_models_published: number;
  total_activations: number;
  total_executions: number;
  total_reviews: number;
  avg_rating: number | null;
}

// Generated UserResponse doesn't have last_login; UserPublicProfile has nullable slug

export interface User {
  id: string;
  email: string;
  name: string;
  organization_id: string;
  is_admin: boolean;
  is_active: boolean;
  created_at: string;
  last_login?: string;
}

export interface UserProfile {
  id: string;
  name: string;
  display_name?: string;
  slug: string;
  bio?: string;
  avatar_url?: string;
  linkedin_url?: string;
  twitter_url?: string;
  organization_id: string;
  organization_name: string;
  organization_verified: boolean;
  total_reviews: number;
  avg_rating_given: number;
}

// Generated ApiKeyInfo has different fields from frontend APIKey

export interface APIKey {
  id: string;
  name: string;
  key_prefix: string;
  description?: string;
  is_active: boolean;
  created_at: string;
  last_used_at?: string;
  expires_at?: string;
}

// Generated ModelCatalogResponse uses `string` for category instead of ModelCategory enum

export interface ModelCatalogItem {
  id: string;
  name: string;
  display_name: string;
  description?: string;
  short_description?: string;
  category: ModelCategory;
  tags: string[];
  version: string;
  is_official: boolean;
  is_featured: boolean;
  total_activations: number;
  total_executions: number;
  avg_execution_time_ms?: number;
  success_rate?: number;
  avg_rating?: number;
  author_organization_id: string;
  author_name: string;
  author_verified: boolean;
  /** Additive: false when the listing has no generator facet nor pinned version
   *  to materialize (legacy demo rows) — the "Use in studio" CTA is disabled. */
  can_open_in_studio?: boolean;
  logo_url?: string | null;
  screenshot_urls?: string[] | null;
  section_overview?: string | null;
  section_features?: string | null;
  section_how_it_works?: string | null;
  section_example_io?: string | null;
  section_changelog?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OrganizationModel {
  id: string;
  organization_id: string;
  catalog_id?: string;
  custom_name?: string;
  display_name: string;
  description?: string;
  category: ModelCategory;
  is_active: boolean;
  is_favorite: boolean;
  total_executions: number;
  last_executed_at?: string;
  created_at: string;
}

export interface FileImportMetadata {
  source_format: string;
  num_variables: number;
  num_constraints: number;
  num_integer: number;
  num_binary: number;
  num_continuous: number;
  file_size_bytes: number;
  original_filename: string;
}

export interface FileImportPreviewResponse {
  problem: _OptimizationProblem;
  metadata: FileImportMetadata;
}

// Generated ModelExecutionResponse uses loose `string` for status/solver_status
// and `Record<string, unknown>` for result_data instead of OptimizationResult.

export interface ModelExecution {
  id: string;
  // P1.5 fusion: the ModelProject this run executed. organization_model_id is
  // served for HISTORIC rows only (its value equals the backfilled project id).
  model_project_id?: string | null;
  organization_model_id: string | null;
  status: ExecutionStatus;
  input_data?: Record<string, unknown>;
  result_data?: _OptimizationResult;
  error_message?: string;
  execution_time_ms?: number;
  solver_status?: _SolverStatus;
  objective_value?: number;
  created_at: string;
  completed_at?: string;
  origin?: ExecutionOrigin;
  trigger_id?: string;
  // Provenance: the object this execution traces back to.
  source_kind?: ExecutionSourceKind | null;
  source_id?: string | null;
  solver_name?: string;
  // Resolved display name + author of the model behind the run (studio
  // ModelProject or activated org model); filled by the history list endpoint.
  model_name?: string | null;
  model_author?: string | null;
  // §8/S1: the named dataset the model was compiled against. `dataset_name`
  // is a snapshot — it survives dataset deletion.
  dataset_id?: string | null;
  dataset_name?: string | null;
}

/** How an execution was created. Mirrors the backend ORIGIN_* slugs. */
export type ExecutionOrigin =
  | "manual"
  | "triggered"
  | "visual_builder"
  | "ai_builder"
  | "template"
  | "import"
  | "marketplace"
  | "api"
  | "mcp";

/** The kind of object an execution can navigate back to. */
export type ExecutionSourceKind =
  | "builder_document"
  | "llm_conversation"
  | "template"
  | "organization_model"
  | "trigger"
  | "imported_file";

export interface AsyncTask {
  task_id: string;
  status: string;
  /** The ModelExecution row id (`exe_…`) — first-class in the async contract
   * (ADR-007 §6): task_id keys Celery/WS, execution_id keys history. Lets a
   * caller deep-link to the full execution-detail page. */
  execution_id?: string;
}

/**
 * The 202 "still running" envelope a solve endpoint returns when a solve outlives
 * the server-side wait budget (ADR-007). The sync client methods resolve it
 * transparently by polling the async task to completion, so callers keep receiving
 * a plain result. `execution_id` is carried here because the polled worker result
 * dump doesn't include it (the sync shaper used to inject it).
 */
export interface AsyncSolveEnvelope {
  task_id: string;
  execution_id: string;
  status: string;
  poll_url?: string;
  ws_url?: string;
  message?: string;
}

export interface AsyncTaskStatus {
  task_id: string;
  status: ExecutionStatus;
  result?: ModelExecution;
  error?: string;
  progress?: number;
}

// Uses intersection type since OptimizationResult is a type alias from the generated file.

export type SolveResult = _OptimizationResult & {
  execution_id: string;
};

/**
 * The Celery task-return envelope nested under an async-solve status once the task
 * completes. The real `SolveResult` lives at `result.result`.
 */
export interface AsyncSolveResultEnvelope {
  status?: string; // "success"
  task_id?: string;
  result?: SolveResult; // the actual solver result
  execution_time_seconds?: number;
  solver_used?: string;
  auto_route_reason?: string;
  warning?: string;
}

/** Status of an async `/solve/async` task (the universal solve, not a marketplace model). */
export interface SolveAsyncStatus {
  task_id?: string;
  status: string; // pending | running | completed | failed
  // On "completed" this is the task envelope (unwrap `result.result`); some paths
  // may return a plain SolveResult — callers unwrap defensively.
  result?: AsyncSolveResultEnvelope | SolveResult;
  error?: string;
  progress?: number;
  solver_used?: string;
  auto_route_reason?: string;
  warning?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}










export interface AnalyticsSummary {
  total_views: number;
  total_impressions: number;
  total_activations: number;
  conversion_rate: number;
  period: string;
}


export interface AdminAnalytics {
  platform_totals: AnalyticsSummary;
}





export interface VerificationRequestStatus {
  id: string;
  organization_id: string;
  status: string;
  admin_note: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export interface AdminVerificationEntry {
  id: string;
  organization_id: string;
  org_name: string;
  profile_completeness: number;
  models_published: number;
  member_since: string;
  status: string;
  created_at: string;
}

export interface NotificationPreferenceEntry {
  event_type: string;
  channel: string;
  enabled: boolean;
}

export interface NotificationPreferencesResponse {
  preferences: NotificationPreferenceEntry[];
}

// Generated NotificationResponse uses loose `string` for type field

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  is_read: boolean;
  data?: Record<string, unknown>;
  created_at: string;
}

export interface NotificationList {
  items: Notification[];
  total: number;
  unread_count: number;
}

// Generated ReviewResponse uses optional `string | null` for fields the frontend expects non-null

export interface Review {
  id: string;
  catalog_id: string;
  user_id: string;
  user_name: string;
  organization_name: string;
  rating: number;
  title?: string;
  comment?: string;
  created_at: string;
  is_visible: boolean;
}

export interface ReviewList {
  items: Review[];
  total: number;
  avg_rating: number;
}

export interface InputField {
  name: string;
  label?: string;
  type: "string" | "number" | "integer" | "boolean" | "array" | "object";
  required?: boolean;
  default?: unknown;
  description?: string;
  minimum?: number;
  maximum?: number;
  enum?: string[];
}

export interface TemplateSummary {
  id: string;
  name: string;
  display_name: string;
  description: string;
  category: string;
  tags: string[];
}

// ── ModelProject (studio workspace; P1e) ────────────────────────────────────
// Handwritten mirror of app/schemas/model_project.py + model_stats.py. The
// generated `api.ts` carries the canonical shapes once regenerated.
export interface CanvasJson {
  nodes?: unknown[];
  edges?: unknown[];
}

export interface ProjectRead {
  id: string;
  organization_id: string;
  workspace_id?: string | null;
  name: string;
  description?: string | null;
  status: string;
  source_type?: string | null;
  source_ref?: string | null;
  current_version_id?: string | null;
  committed_count: number;
  draft_model_json?: _OptimizationProblem | null;
  draft_canvas_json?: CanvasJson | null;
  draft_dsl_source?: string | null;
  draft_content_hash?: string | null;
  draft_lock_version: number;
  draft_updated_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProjectListItem {
  id: string;
  name: string;
  description?: string | null;
  status: string;
  source_type?: string | null;
  current_version_id?: string | null;
  committed_count: number;
  updated_at: string;
  created_by?: string | null;
  created_by_name?: string | null;
}

/** A single JModel (DSL) lex/parse/grounding error (POST /api/v2/dsl/compile). */
export interface DslCompileError {
  message: string;
  position?: number | null;
}

/** Result of compiling JModel source: ok=true → problem, ok=false → error. */
export interface DslCompileResult {
  ok: boolean;
  problem?: _OptimizationProblem | null;
  error?: DslCompileError | null;
}

/** Whether the JModel DSL feature is enabled on this instance (GET /api/v2/dsl/status). */
export interface DslStatusResult {
  enabled: boolean;
}

/** A declared set as listed by POST /api/v2/dsl/inspect (S2a). */
export interface DslSetDecl {
  name: string;
  has_inline_values: boolean;
}

/** A declared param: its index sets define the dataset key shape. */
export interface DslParamDecl {
  name: string;
  index_sets: string[];
  arity: number;
  has_inline_values: boolean;
}

/** Parse-only view of a source's declarations (skeleton + live validation). */
export interface DslInspectResult {
  ok: boolean;
  sets?: DslSetDecl[] | null;
  params?: DslParamDecl[] | null;
  error?: DslCompileError | null;
}

/** One rendered LaTeX line plus the source name (POST /api/v2/dsl/latex, B1). */
export interface DslLatexLine {
  latex: string;
  label?: string | null;
}

/** A JModel rendered as symbolic math: objective, constraint families, domains. */
export interface DslLatexModel {
  objective?: DslLatexLine | null;
  constraints: DslLatexLine[];
  variables: DslLatexLine[];
}

/** Parse-only symbolic-math view of a source (the JModel split-pane, B1). */
export interface DslLatexResult {
  ok: boolean;
  model?: DslLatexModel | null;
  error?: DslCompileError | null;
}

/**
 * A named data bundle ("scenario") for a project's parametric JModel: set members
 * + param values that fill a declaration-only source at compile time (§8).
 * `data_json` = `{"sets": {...}, "params": {...}}` — composite param keys are
 * comma-joined (`"A,1": 4`). The list endpoint returns the summary (no values).
 */
export interface ProjectDatasetSummary {
  id: string;
  model_project_id: string;
  name: string;
  description?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

/** A parsed data file (S2c) — a preview the user names and saves via the normal create. */
export interface DatasetImportPreview {
  data_json: Record<string, unknown>;
  suggested_name: string;
}

export interface ProjectDataset extends ProjectDatasetSummary {
  data_json: Record<string, unknown>;
}

/**
 * A compact execution row used to RECONCILE a solve from the server when the
 * workspace opens (durable, server-derived solve sessions). A running async row
 * is re-attached by `celery_task_id`; a terminal one surfaces as the "last run".
 */
export interface ProjectExecutionItem {
  id: string;
  status: string; // pending | running | completed | failed | cancelled | timeout
  is_async: boolean;
  celery_task_id?: string | null;
  solver_name?: string | null;
  objective_value?: number | null;
  model_project_version_id?: string | null;
  execution_time_ms?: number | null;
  // §8/S1: dataset provenance (name is a deletion-surviving snapshot).
  dataset_id?: string | null;
  dataset_name?: string | null;
  error_message?: string | null;
  created_at: string;
  started_at?: string | null;
  completed_at?: string | null;
}

export interface ProjectVersionSummary {
  id: string;
  sequence: number;
  commit_summary: string;
  problem_class?: string | null;
  created_by?: string | null;
  created_at: string;
}

export interface ProjectVersionRead extends ProjectVersionSummary {
  model_project_id: string;
  parent_version_id?: string | null;
  commit_body?: string | null;
  content_hash: string;
  model_json: _OptimizationProblem;
  canvas_json?: CanvasJson | null;
  dsl_source?: string | null;
  stats_json?: Record<string, unknown> | null;
}

export interface ProjectVersionDiffEntry {
  kind: string;
  change: string;
  name: string;
  detail?: string | null;
}

export interface ProjectVersionDiff {
  from_version_id: string;
  to_version_id: string;
  entries: ProjectVersionDiffEntry[];
  objective_changed: boolean;
}

export interface DraftUpdateBody {
  model_json?: Record<string, unknown> | null;
  canvas_json?: Record<string, unknown> | null;
  dsl_source?: string | null;
}

export type ModelHealthBand = "A" | "B" | "C" | "D" | "F";

export interface ModelHealthDeduction {
  code: string;
  points: number;
  detail: string;
}

export interface ModelHealth {
  score: number;
  band: ModelHealthBand;
  deductions: ModelHealthDeduction[];
  has_hard_error: boolean;
}

export interface ModelStatsBoundProfile {
  free: number;
  boxed: number;
  one_sided: number;
  binary: number;
  integers_missing_bounds: number;
}

export interface ModelStatsConditioning {
  min_abs?: number | null;
  max_abs?: number | null;
  range_ratio?: number | null;
  tier: "ok" | "mild" | "poor" | "severe";
}

export interface ModelStats {
  var_total: number;
  var_continuous: number;
  var_integer: number;
  var_binary: number;
  constraint_total: number;
  constraints_by_operator: Record<string, number>;
  objective_sense?: string | null;
  objective_terms: number;
  objective_quadratic: boolean;
  nonzeros: number;
  density: number;
  integrality_ratio: number;
  bound_profile: ModelStatsBoundProfile;
  conditioning: ModelStatsConditioning;
  problem_class?: string | null;
  warnings: string[];
  health: ModelHealth;
  content_hash: string;
}

export interface BuilderDocument {
  id: string;
  organization_id: string;
  created_by: string | null;
  name: string;
  canvas_json: Record<string, unknown>;
  model_json: Record<string, unknown> | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface BuilderDocumentListItem {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface AdminStats {
  organizations: { total: number; active: number };
  users: { total: number; active: number };
  api_keys: { total: number; active: number };
  models: { catalog_total: number; catalog_public: number; activated_total: number };
}

export interface AdminOrganizationSummary {
  id: string;
  name: string;
  plan: string;
  user_count: number;
  created_at: string;
}

export interface AdminUserSummary {
  id: string;
  name: string;
  email: string;
  organization_id: string;
  role: string;
  is_active: boolean;
  created_at: string;
}

export interface AdminUser extends AdminUserSummary {
  last_login_at: string | null;
  updated_at: string;
}

export interface AdminAPIKey {
  id: string;
  name: string;
  description?: string;
  key_prefix: string;
  organization_id: string;
  user_id: string;
  is_active: boolean;
  created_at: string;
  last_used_at: string | null;
  full_key?: string;
}

// Generated TriggerResponse uses `Record<string, unknown>[]` for override_schema,
// and uses loose `string` for status/source fields.

export interface SolveTrigger {
  id: string;
  organization_id: string;
  created_by: string | null;
  name: string;
  description?: string;
  document_id: string;
  version_id: string;
  workspace_id?: string | null;
  override_schema: _OverrideField[] | null;
  webhook_url: string;
  is_enabled: boolean;
  total_runs: number;
  last_fired_at?: string;
  trigger_secret_prefix: string;
  created_at: string;
  updated_at: string;
}

export interface CreateTriggerResponse extends SolveTrigger {
  trigger_secret: string;
}

export interface TriggerRun {
  id: string;
  trigger_id: string;
  organization_id: string;
  source: "manual" | "cron" | "rerun";
  status: TriggerRunStatus;
  execution_id?: string | null;
  override_data?: Record<string, unknown>;
  result_data?: Record<string, unknown>;
  error_message?: string;
  execution_time_ms?: number;
  webhook_delivered?: boolean;
  webhook_attempts: number;
  created_at: string;
  completed_at?: string;
}

export interface CreateTriggerRequest {
  name: string;
  description?: string;
  document_id: string;
  version_id: string;
  override_schema?: _OverrideField[];
  webhook_url: string;
  webhook_secret?: string;
  workspace_id?: string;
}

export interface TriggerSchedule {
  id: string;
  trigger_id: string;
  cron_expression: string;
  timezone: string;
  is_enabled: boolean;
  consecutive_failures: number;
  last_run_at: string | null;
  next_run_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface GuidanceState {
  skill_level: _SkillLevel;
  wizard_step: number;
  wizard_dismissed: boolean;
  wizard_completed: boolean;
}

// Generated WorkspaceResponse/WorkspaceMemberResponse use loose `string` for role field

export interface Workspace {
  id: string;
  name: string;
  description: string | null;
  is_active: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  member_count: number;
  pool_allocated: number | null;
  pool_used: number | null;
}

export interface WorkspaceMember {
  id: string;
  user_id: string;
  user_name: string;
  user_email: string;
  role: WorkspaceRole;
  joined_at: string;
  invited_by: string | null;
}

export interface WorkspaceInvite {
  id: string;
  workspace_id: string;
  role: WorkspaceRole;
  method: "email" | "link";
  invitee_email: string | null;
  created_at: string;
  expires_at: string;
  is_revoked: boolean;
}

export interface AuditLogEntry {
  id: string;
  workspace_id: string | null;
  actor_id: string;
  actor_name: string;
  action: string;
  target_type: string | null;
  target_id: string | null;
  target_name: string | null;
  before_state: Record<string, unknown> | null;
  after_state: Record<string, unknown> | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface SolveAnalyticsSummary {
  total_executions: number;
  completed: number;
  failed: number;
  timed_out: number;
  success_rate: number;
  avg_solve_time_ms: number | null;
  median_solve_time_ms: number | null;
  avg_objective_value: number | null;
  executions_by_status: Record<string, number>;
  executions_by_origin: Record<string, number>;
  solver_status_distribution: Record<string, number>;
}

export interface TrendBucket {
  date: string;
  executions: number;
  completed: number;
  failed: number;
  avg_solve_time_ms: number | null;
}

export interface SolveAnalyticsTrends {
  days: number;
  bucket: string;
  data: TrendBucket[];
}

export interface ComparedExecution {
  id: string;
  status: string;
  solver_status: string | null;
  objective_value: number | null;
  execution_time_ms: number | null;
  created_at: string;
  origin: string;
  num_variables: number | null;
  num_constraints: number | null;
  gap: number | null;
}

export interface SolveAnalyticsCompare {
  executions: ComparedExecution[];
}
