"""Formulation validation for LLM-generated optimization problems.

Reuses the variable extraction logic from app/api/v2/solve.py
(copied and adapted to work on formulation dicts rather than Pydantic models).

Handles parametric/abstract formulations generated by LLMs, which use
summation operators (sum_j), quantifier clauses (for all i), index
variables (i, j, k), and parameters (capacity, weight_i) that should
not be flagged as undeclared variables.
"""

import re
from typing import Any


def validate_formulation(formulation: dict[str, Any]) -> list[dict[str, Any]]:
    """Validate a structured formulation dict.

    Checks for:
    - Empty variables list
    - Invalid variable bounds (lower > upper)
    - Undeclared variables referenced in constraints/objective
    - Empty constraints (warning, not error)

    Handles parametric formulations where expressions contain summation
    operators, quantifier clauses, index variables, and problem parameters.

    Args:
        formulation: Dict matching the Formulation schema.

    Returns:
        List of error/warning dicts with keys: field, index, message, suggestion.
    """
    errors: list[dict[str, Any]] = []

    variables = formulation.get("variables", [])
    constraints = formulation.get("constraints", [])
    objective = formulation.get("objective", {})

    # Check: empty variables
    if not variables:
        errors.append(
            {
                "field": "variable",
                "index": None,
                "message": "No variables defined. A formulation needs at least one decision variable.",
                "suggestion": "Add variables representing the decisions in your problem.",
            }
        )
        return errors  # Can't do further checks without variables

    # Collect declared variable names
    declared_vars = set()
    for i, var in enumerate(variables):
        name = var.get("name", "")
        if not name:
            errors.append(
                {
                    "field": "variable",
                    "index": i,
                    "message": f"Variable at index {i} has no name.",
                    "suggestion": "Give this variable a descriptive name.",
                }
            )
            continue
        declared_vars.add(name)

        lb = var.get("lower_bound")
        ub = var.get("upper_bound")
        if lb is not None and ub is not None and lb > ub:
            errors.append(
                {
                    "field": "variable",
                    "index": i,
                    "message": (
                        f"Variable '{name}' has invalid bounds: "
                        f"lower_bound ({lb}) > upper_bound ({ub})."
                    ),
                    "suggestion": f"Swap the bounds or adjust them for '{name}'.",
                }
            )

    family_prefixes = _build_family_prefixes(declared_vars)

    for i, constraint in enumerate(constraints):
        expr = constraint.get("expression", "")
        referenced = _extract_variable_names(expr)
        undeclared = _filter_undeclared(referenced, declared_vars, family_prefixes)
        if undeclared:
            for var_name in sorted(undeclared):
                errors.append(
                    {
                        "field": "constraint",
                        "index": i,
                        "message": (
                            f"Constraint '{constraint.get('name', f'#{i}')}' references "
                            f"undeclared variable '{var_name}'."
                        ),
                        "suggestion": f"Add '{var_name}' as a variable, or fix the expression.",
                    }
                )

    obj_expr = objective.get("expression", "")
    if obj_expr:
        obj_referenced = _extract_variable_names(obj_expr)
        obj_undeclared = _filter_undeclared(obj_referenced, declared_vars, family_prefixes)
        if obj_undeclared:
            for var_name in sorted(obj_undeclared):
                errors.append(
                    {
                        "field": "objective",
                        "index": None,
                        "message": (f"Objective references undeclared variable '{var_name}'."),
                        "suggestion": f"Add '{var_name}' as a variable, or fix the expression.",
                    }
                )

    # Warning: empty constraints (unusual but valid)
    if not constraints:
        errors.append(
            {
                "field": "constraint",
                "index": None,
                "message": "No constraints defined. This is unusual for an optimization problem.",
                "suggestion": "Consider adding constraints that limit the feasible region.",
            }
        )

    return errors


# Tokens excluded from variable extraction — math functions, keywords,
# natural language words common in parametric formulations.
_EXCLUDED_TOKENS = {
    # Math functions
    "sin",
    "cos",
    "tan",
    "exp",
    "log",
    "sqrt",
    "abs",
    "min",
    "max",
    "sum",
    "prod",
    "if",
    "else",
    "and",
    "or",
    "not",
    # Single-letter index variables
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "N",
    "M",
    "K",
    "L",
    "T",
    # Quantifier / natural language words
    "for",
    "all",
    "each",
    "every",
    "where",
    "such",
    "that",
    "with",
    "in",
    "of",
    "to",
    "the",
    "is",
    "are",
    "be",
    "items",
    "bins",
    "consecutive",
    "pairs",
    "over",
    "from",
}


def _extract_variable_names(expression: str) -> set[str]:
    """Extract variable names from a mathematical expression.

    Handles parametric/abstract formulations by:
    1. Stripping quantifier clauses (``for all ...``, ``∀ ...``)
    2. Stripping summation/product operator notation (``sum_j(...)``)
    3. Removing curly-brace index notation (``{j+1}``)
    4. Filtering out known non-variable tokens

    Args:
        expression: Mathematical expression string.

    Returns:
        Set of candidate variable name strings.
    """
    expr = expression

    # 1. Strip quantifier clauses — everything from "for all/each/every" or "∀" to end
    expr = re.sub(r"\b(for\s+(all|each|every))\b.*", "", expr, flags=re.IGNORECASE)
    expr = re.sub(r"∀.*", "", expr)

    # 2. Strip summation/product operator notation: sum_j(...) → inner content
    #    Handles nested parens via simple greedy match on balanced content.
    expr = re.sub(r"\b(sum|prod)_[a-zA-Z0-9_]*\(", "(", expr, flags=re.IGNORECASE)

    # 3. Remove curly-brace index notation: {j+1}, {i}, etc.
    expr = re.sub(r"\{[^}]*\}", "", expr)

    # 4. Tokenize and filter
    tokens = re.findall(r"[a-zA-Z_][a-zA-Z0-9_]*", expr)
    return {t for t in tokens if t not in _EXCLUDED_TOKENS}


def _build_family_prefixes(declared_vars: set[str]) -> set[str]:
    """Build family prefixes from declared variable names.

    For parametric variables like ``assign_i_j`` or ``bin_used_j``,
    strips trailing index suffixes (``_i``, ``_j``, ``_ij``, ``_1``, etc.)
    to produce a base prefix. Tokens in expressions that share the same
    prefix are considered members of the same variable family.

    Args:
        declared_vars: Set of declared variable names.

    Returns:
        Set of prefix strings (e.g. ``{"assign", "bin_used"}``).
    """
    prefixes: set[str] = set()
    for name in declared_vars:
        # Strip trailing index suffixes: _i, _j, _ij, _1, _12, etc.
        # Repeatedly strip from the end to handle multi-index like _i_j
        base = name
        while True:
            # Match trailing _<single-letter> or _<digits>
            m = re.match(r"^(.+?)_([a-zA-Z]|[0-9]+)$", base)
            if m and len(m.group(1)) >= 2:
                base = m.group(1)
            else:
                break
        if base != name:
            prefixes.add(base)
    return prefixes


def _has_index_suffix(token: str) -> bool:
    """Check if a token ends with an index-like suffix (_i, _j, _1, etc.)."""
    return bool(re.search(r"_([a-zA-Z]|[0-9]+)$", token))


def _filter_undeclared(
    referenced: set[str],
    declared_vars: set[str],
    family_prefixes: set[str],
) -> set[str]:
    """Filter referenced tokens to find truly undeclared variables.

    A token is NOT flagged if:
    - It exactly matches a declared variable
    - It starts with a known variable family prefix followed by ``_``
    - It is 2 characters or fewer (likely an index or abbreviation)
    - It ends with an index suffix like ``_i``, ``_j`` (likely a parameter)
    - The formulation is parametric (has family prefixes) and the token
      looks like a problem parameter rather than a decision variable

    Args:
        referenced: Tokens extracted from an expression.
        declared_vars: Set of declared variable names.
        family_prefixes: Set of variable family prefixes.

    Returns:
        Set of tokens that are likely truly undeclared variables.
    """
    is_parametric = len(family_prefixes) > 0
    undeclared: set[str] = set()
    for token in referenced:
        # Exact match
        if token in declared_vars:
            continue
        # Short tokens (<=2 chars) are likely indices or abbreviations
        if len(token) <= 2:
            continue
        # Family prefix match: e.g. token "assign_3_5" matches prefix "assign"
        if any(token.startswith(prefix + "_") for prefix in family_prefixes):
            continue
        # Token itself is a prefix (partial reference like "bin_used")
        if token in family_prefixes:
            continue
        # Tokens with index suffixes are likely indexed parameters (weight_i, cost_j)
        if _has_index_suffix(token):
            continue
        # In parametric formulations, remaining tokens are assumed to be
        # problem parameters (capacity, demand, etc.), not undeclared variables
        if is_parametric:
            continue
        undeclared.add(token)
    return undeclared
